// ===========================
// FINANCEAI PRO — LANG.JS
// i18n Architecture v2.0
// Climberforsuccess LLC
// ===========================

const TRANSLATIONS = {
  en: {
    // NAVBAR
    nav_features:    'Features',
    nav_pricing:     'Pricing',
    nav_login:       'Login',
    nav_start:       'Start Free',

    // HERO
    hero_badge:      '✨ POWERED BY AI — FREE TO START',
    hero_title:      'Take Control of your <span style="color:#00EEFF">Finances</span> with Artificial Intelligence',
    hero_desc:       'Scan receipts, manage debts, discover the best cards and get personalized AI recommendations. All in one place.',
    hero_cta:        '🚀 Start Free Now',
    hero_demo:       'Watch Demo',
    stat1:           'Active Users',
    stat2:           'In Managed Debts',
    stat3:           'Compatible Cards',
    stat4:           'Average Rating',

    // FEATURES SECTION
    feat_title:      'Everything you need for your finances',
    feat_sub:        'Powerful features powered by artificial intelligence',
    f1_title:        'AI Receipt Scanner',
    f1_desc:         'Photograph any receipt and our AI automatically detects the amount, category, date and merchant.',
    f2_title:        'Best Card for Each Purchase',
    f2_desc:         'Get recommendations on which card to use based on benefits, cashback and available points.',
    f3_title:        'Debt Payoff Plan',
    f3_desc:         'Personalized strategies to pay off your debts faster using Avalanche and Snowball methods.',
    f4_title:        'AI Financial Assistant',
    f4_desc:         'Ask anything about your finances and get personalized advice based on your real data.',
    f5_title:        'Subscription Manager',
    f5_desc:         'Automatically detect your active subscriptions, alert you before charges and calculate monthly spend.',
    f6_title:        'Personal vs Business',
    f6_desc:         'Automatically separate personal and business expenses to keep your finances organized.',

    // PRICING SECTION
    price_title:     'Plans & Pricing',
    price_sub:       'Start free, scale when you are ready',
    billing_monthly: 'Monthly',
    billing_annual:  'Annual',
    billing_save:    '-20%',
    billing_banner:  '🎉 Annual plan saves you up to $120/year — 2 months FREE',
    plan_popular:    'Most Popular',
    plan_current:    'Current plan',
    plan_month:      '/mo',
    plan_year:       '/yr',
    period_personal: '/mo',
    period_pro:      '/mo',
    period_business: '/mo',
    plan_free_btn:   'Free forever',
    plan_pers_btn:   'Get Personal',
    plan_pro_btn:    'Get Pro',
    plan_biz_btn:    'Get Business',

    // SIDEBAR NAV
    nav_dash:         'Dashboard',
    dash_limit_reached: 'Limit reached:',
    dash_upgrade:       'Upgrade your plan',
    dash_txs_used:      'transactions used',
    dash_consider_upgrade: 'Consider upgrading',
    tx_empty:    'You have no transactions yet.',
    tx_no_desc:  'No description',
    nav_scan:        'AI Scanner',
    nav_trans:       'Transactions',
    nav_cards:       'My Cards',
    nav_debts:       'Debts',
    nav_subs:        'Subscriptions',
    nav_recs:        'Recommendations',
    nav_ai:          'AI Assistant',
    nav_rep:         'Reports',
    nav_set:         'Settings',
    nav_logout:      'Log Out',

    // DASHBOARD
    dash_title:      'Dashboard',
    dash_sub:        'Financial summary for this month',
    lbl_income:      'Monthly Income',
    lbl_expense:     'Monthly Expenses',
    lbl_balance:     'Available Balance',
    lbl_debt:        'Total Debt',
    lbl_recent:      'Recent Transactions',
    lbl_subs:        'Active Subscriptions',
    lbl_debts:       'Debt Plan',
    dash_view_all:   'View all',
    dash_ai_title:   '🤖 AI Assistant',
    dash_ai_online:  'Online',
    dash_chat_ph:    'Ask me something about your finances...',
    dash_vs_last:        '↑ % vs last month',
    dash_healthy:        '✓ Healthy finances',
    dash_debt_month:     '↓ this month',
    dash_messages_left:  'messages today',

    // TRANSACTIONS
    trans_title:     'Transactions',
    trans_add:       'Add Transaction',
    trans_all:       'All',
    trans_income:    'Income',
    trans_expense:   'Expense',
    trans_empty:     'No transactions yet',

    // CARDS
    cards_title:     'My Cards',
    cards_add:       'Add Card',
    card_healthy:     'Healthy',
    card_warning:     'Caution',
    card_danger:      'High use',
    card_holder:      'HOLDER',
    card_limit_label: 'LIMIT',
    card_no_name:     'No name',
    card_due:         'Due day',
    cards_personal:   '👤 Personal Cards',
    cards_business:   '🏢 Business Cards',
    card_edit_title:  '✏️ Edit Card',
    card_name_bank:   'Name / Bank',
    card_type_label:  'Type',
    card_limit_lbl:   'Limit ($)',
    card_balance_lbl: 'Used balance ($)',
    card_last4:       'Last 4 digits',
    card_apr:         'APR (%)',
    card_color:       'Card color',
    card_due_day:     'Due day',
    card_name_required: 'Name is required',
    card_updated:     '✅ Card updated',
    card_save_error:  'Error saving changes',
    card_deleted:     'Card deleted',
    card_delete_error:'Error deleting card',
    btn_cancel:       'Cancel',
    btn_save:         '💾 Save Changes',
    debt_add_title:    '📉 Add Debt',
    debt_name_label:      'Name (Card / Loan)',
    debt_name_placeholder:'e.g. Chase Visa...',
    debt_balance_label:   'Current Balance ($)',
    debt_min_label:       'Monthly Minimum Payment ($)',
    debt_save_btn:        '💾 Save Debt',
    debt_invalid_balance: 'Enter a valid balance',
    session_expired:      'Session expired',
    debt_added:           '✅ Debt added!',
    debt_save_error:      'Error saving debt',
    debt_deleted:         'Debt deleted',
    debt_delete_error:    'Error deleting debt',
    debts_empty:          'You have no debts registered.',
    debt_priority_high:   'HIGH Priority',
    debt_priority_med:    'MEDIUM Priority',
    debt_priority_low:    'Minimum payment for now',
    debt_used:            'used',
    debt_of:              'of',
    debt_utilized:        'utilized',
    debt_min_pay:         'Minimum payment',
    btn_delete:           'Delete',
    debts_personal:       'Personal Debts',
    debts_business:       'Business Debts',
    time_years:           'years',
    time_months:          'months',
    method_avalanche:     '❄️ Avalanche Method',
    method_snowball:      '⛄ Snowball Method',
    toast_avalanche:      '📊 Avalanche: You pay less interest overall!',
    toast_snowball:       '⛄ Snowball: More motivation to keep going!',
    cards_limit:     'Credit Limit',
    cards_used:      'Used',
    cards_available: 'Available',
    cards_empty:     'No cards added yet',

    // DEBTS
    debts_title:     'Debts',
    debts_total:     'Total Debt',
    debts_payoff:    'Estimated Payoff',
    debts_method:    'Payoff Method',
    debts_add:       'Add Debt',
    debt_method_title: '❄️ Avalanche Method',
    debt_ai_recs:    '💡 AI Recommendations',

    // SUBSCRIPTIONS
    subs_title:      'Subscriptions',
    subs_total:      'Total Monthly',
    subs_count:      'Active Subscriptions',
    subs_add:        'Add Subscription',
    subs_empty:      'No subscriptions yet',

    // SCANNER
    scan_title:      'AI Receipt Scanner',
    scan_upload:     'Drop your receipt here or click to upload',
    scan_formats:    'Supports JPG, PNG, PDF',
    scan_analyzing:  'Analyzing receipt...',
    scan_merchant:   'Merchant',
    scan_amount:     'Amount',
    scan_date:       'Date',
    scan_category:   'Category',
    scan_save:       'Save Expense',

    // REPORTS
    rep_title:       'Reports',
    rep_cat:         '📊 Expenses by Category',
    rep_monthly:     '📅 Monthly Summary 2025',

    // SETTINGS
    set_title:       'Settings',
    set_profile:     '👤 Profile',
    set_subtitle:    'Customize your experience',
    lbl_name:        'Name',
    lbl_email:       'Email',
    lbl_country:     'Country',
    set_currency:    'Currency',
    set_language:    '🌐 Language',
    set_plan:        '💳 Choose your plan',
    set_notif:       '🔔 Notifications',
    set_danger:      '⚠️ Danger Zone',
    set_legal:       '⚖️ Legal',
    set_save:        'Save Changes',
    set_logout_all:  'Log Out of All Devices',
    set_delete:      'Delete Account',

    // GENERAL
    general_save:    'Save',
    general_cancel:  'Cancel',
    general_delete:  'Delete',
    general_edit:    'Edit',
    general_add:     'Add',
    general_close:   'Close',
    general_loading: 'Loading...',
    general_yes:     'Yes, delete',
    general_personal:'Personal',
    general_business:'Business',

    // TOASTS
    toast_saved:     'Saved successfully',
    toast_deleted:   'Deleted successfully',
    toast_error:     'Error. Please try again.',

    // UPGRADE MODAL
    upgrade_title:   'Upgrade your plan',
    upgrade_cta:     'See Plans',
    upgrade_cancel:  'Maybe later',

    // LIMIT BANNERS
    limit_reached:   '🚫 Limit reached',
    limit_warning:   '⚠️ used — Consider upgrading',
    limit_upgrade:   'Upgrade your plan',

    // AI CHAT
    ai_welcome:      '👋 Hi! I\'m your FinanceAI assistant. How can I help you today?',
    ai_placeholder:  'Ask me something about your finances...',
    ai_thinking:     '💭 Thinking...',
    ai_msgs_left:    'messages today',
    debt_tip_text:       'Pay the card with the highest interest rate first.',
    credit_score_warn:   'Your credit score may drop. Prioritize reducing this card first.',
    badge_vence_pronto:  'Expiring soon',
    rec_based_on:        'Based on your transactions: you spend most on ',
    rec_desc_default:    'Available in Mexico, Colombia and Brazil. No hidden fees, full control from the app.',
    no_trans_yet:        'No transactions yet',
    sub_scanner:         'Subscription scanner',
    badge_popular:       '🔥 MOST POPULAR',
    notif_label_4:       'Payment reminders',
    danger_zone_title:   '⚠️ Danger Zone',
    delete_account_btn:  'Delete Account',
    legal_title:         '⚖️ Legal',
    legal_terms_title:   '📋 Terms of Service',
    legal_terms_desc:    'FinanceAI Pro terms and conditions',
    legal_privacy_title: '🔒 Privacy Policy',
    legal_privacy_desc:  'How we protect your data',
    copyright_text:      '© 2025 Climberforsuccess LLC · All rights reserved',
    admin_page_title:    '🔐 Admin Panel',
    admin_page_subtitle: 'Climberforsuccess LLC — Control Panel',
    admin_label_total:   '👥 Total Users',
    admin_label_vip:     '👑 VIP Users',
    admin_label_codes:      '🎁 Codes Used',
    admin_label_ai_calls:   '🤖 AI Calls Today',
    admin_vip_mgmt_title:   '🎁 VIP Code Management',
    admin_gen_code_label:   'Generate new code:',
    admin_opt_personal:     '⚡ VIP Personal',
    admin_opt_familia:      '👨‍👩‍👧 VIP Family',
    admin_opt_1m:           '1 month',
    admin_opt_3m:           '3 months',
    admin_opt_6m:           '6 months',
    admin_opt_12m:          '1 year',
    admin_gen_code_btn:     '✨ Generate Code',
    admin_code_generated:   'Generated code:',
    admin_copy_btn:         '📋 Copy',
    admin_session_codes:    'Codes generated this session:',
    admin_no_codes_msg:     'No codes generated yet',
    admin_used_codes_title: '📊 VIP Codes Used',
    admin_loading_msg:      'Loading...',
    admin_activate_vip:     '🌟 Activate VIP Plan',
    vip_status_sub_text:    '5 AI messages per day',
    admin_vip_enter_label:  'Have a VIP code? Enter it here:',
    activate_vip_btn:    'Activate',
    or_buy_plan:         'or buy a plan',
    vip_personal_name:   '⚡ VIP Personal',
    vip_personal_badge:  'Popular',
    vip_personal_f1:     '✅ Unlimited AI messages',
    vip_personal_f2:     '✅ Full GPT-4o access',
    vip_personal_f4:     '✅ Advanced reports',
    get_vip_personal:    '🚀 Get VIP Personal',
    vip_familia_name:    '👨‍👩‍👧 VIP Family',
    vip_familia_f1:      '✅ Everything in Personal',
    vip_familia_f2:      '✅ Up to 5 family accounts',
    vip_familia_f3:      '✅ Shared family dashboard',
    vip_familia_f4:      '✅ Priority support',
    get_vip_familia:     '👨‍👩‍👧 Get VIP Family',
    legal_back_btn:      '← Back',
    modal_upgrade_title: 'Upgrade Your Plan',
    btn_monthly:         'Monthly',
    btn_annual:          'Annual',
    btn_annual_save:     'Save 17%',
    tab_stripe:          '💳 Card (Stripe)',
    tab_paypal:          '🅿️ PayPal',
    modal_secure:        '🔒 Secure • Cancel anytime • No hidden fees',
    feat_unlimited_tx:  'Unlimited transactions',
    feat_basic_reports: 'Basic reports',
    feat_all_pro:       'Everything in Pro',
    feat_5_users:       'Up to 5 users',
    feat_admin_panel:   'Admin panel',
    feat_biz_reports:   'Business reports',
    feat_support_247:   'Priority support 24/7',
    lbl_login_pass:     'Password',
    lbl_reg_name:       'Full Name',
    lbl_reg_plan:       'Plan',
    nav_admin_label:    'Admin Panel',
    scan_tip_1:         'Make sure the receipt is fully visible',
    scan_tip_2:         'Good lighting for better recognition',
    scan_tip_3:         'Keep the phone steady when photographing',
    scan_tip_4:         'Works with receipts in English and Spanish',
    plan_pro_name:       '💎 Pro',
    plan_pro_real_price: 'Real value $39.99/mo',
    pro_f1:              '✅ <strong>Unlimited AI 24/7</strong>',
    pro_f2:              '✅ <strong>GPT-4o</strong> — the most advanced AI',
    pro_f3:              '✅ Unlimited transactions · Up to 10 cards',
    pro_f4:              '✅ Smart receipt scanner',
    pro_f5:              '✅ Advanced reports with insights',
    pro_f6:              '✅ AI financial goals',
    pro_f7:              '✅ <strong>Save $340/mo on average</strong>',
    cta_pro_label:       '⚡ I want to save $340/mo — ',
    pro_cancel_note:     '✅ Cancel anytime · 100% secure payment',
    plan_business_name:  '🏢 Business',
    biz_f1:              '✅ Everything in Pro',
    biz_f2:              '✅ Up to 5 users',
    biz_f3:              '✅ Team management',
    biz_f4:              '✅ Business reports',
    biz_f5:              '✅ Priority support 24/7',
    biz_f6:              '✅ API Access for integrations',
    biz_f7:              '✅ Unlimited cards and users',
    biz_f8:              '✅ <strong>Guaranteed ROI or money back</strong>',
    cta_business_label:  '🏢 Power your business — ',
    testimonial_quote:   '"I recovered $180 in the first month detecting forgotten subscriptions and unnecessary expenses"',
    testimonial_author:  '— María G., Pro user since 2024',
    vip_code_label:      'Do you have a VIP code?',
    notif_label_1:       'Subscription alerts',
    notif_label_2:       'Unusual expenses',
    notif_label_3:       'Weekly summary',
    current_plan_label:   '✨ Current plan: FREE',
    pricing_tagline:      'Invest less than a coffee a day and recover hundreds a month',
    plan_free_name:       '🆓 Free',
    plan_free_period:     '/mo',
    modal_free_f5:        '❌ No advanced reports',
    modal_free_f6:        '❌ No GPT-4o',
    btn_free_label:       'Free forever',
    billing_monthly:      'Monthly',
    billing_annual:       'Annual',
    annual_savings_text:  '🎉 Pay annually and save up to <strong>$120/yr</strong> — 2 months FREE',
    plan_personal_name:   '⭐ Personal',
    modal_personal_f1:    '✅ Unlimited transactions',
    modal_personal_f2:    '✅ Basic reports',
    modal_personal_f3:    '❌ No GPT-4o',
    cta_personal_label:   '🚀 Start now — Only ',
    badge_popular:       '🔥 MÁS POPULAR',
    notif_label_4:       'Recordatorio de pagos',
    danger_zone_title:   '⚠️ Zona de Peligro',
    delete_account_btn:  'Eliminar Cuenta',
    legal_title:         '⚖️ Legal',
    legal_terms_title:   '📋 Términos de Servicio',
    legal_terms_desc:    'Condiciones de uso de FinanceAI Pro',
    legal_privacy_title: '🔒 Política de Privacidad',
    legal_privacy_desc:  'Cómo protegemos tus datos',
    copyright_text:      '© 2025 Climberforsuccess LLC · Todos los derechos reservados',
    admin_page_title:    '🔐 Admin Panel',
    admin_page_subtitle: 'Climberforsuccess LLC — Panel de Control',
    admin_label_total:   '👥 Usuarios Totales',
    admin_label_vip:     '👑 Usuarios VIP',
    admin_label_codes:      '🎁 Códigos Usados',
    admin_label_ai_calls:   '🤖 Llamadas IA Hoy',
    admin_vip_mgmt_title:   '🎁 Gestión de Códigos VIP',
    admin_gen_code_label:   'Generar nuevo código:',
    admin_opt_personal:     '⚡ VIP Personal',
    admin_opt_familia:      '👨‍👩‍👧 VIP Familia',
    admin_opt_1m:           '1 mes',
    admin_opt_3m:           '3 meses',
    admin_opt_6m:           '6 meses',
    admin_opt_12m:          '1 año',
    admin_gen_code_btn:     '✨ Generar Código',
    admin_code_generated:   'Código generado:',
    admin_copy_btn:         '📋 Copiar',
    admin_session_codes:    'Códigos generados esta sesión:',
    admin_no_codes_msg:     'No hay códigos generados aún',
    admin_used_codes_title: '📊 Códigos VIP Usados',
    admin_loading_msg:      'Cargando...',
    admin_activate_vip:     '🌟 Activar Plan VIP',
    vip_status_sub_text:    '5 mensajes IA por día',
    admin_vip_enter_label:  '¿Tienes un código VIP? Ingrésalo aquí:',
    activate_vip_btn:    'Activar',
    or_buy_plan:         'o compra un plan',
    vip_personal_name:   '⚡ VIP Personal',
    vip_personal_badge:  'Popular',
    vip_personal_f1:     '✅ Mensajes IA ilimitados',
    vip_personal_f2:     '✅ GPT-4o acceso completo',
    vip_personal_f4:     '✅ Reportes avanzados',
    get_vip_personal:    '🚀 Obtener VIP Personal',
    vip_familia_name:    '👨‍👩‍👧 VIP Familia',
    vip_familia_f1:      '✅ Todo lo de Personal',
    vip_familia_f2:      '✅ Hasta 5 cuentas familiares',
    vip_familia_f3:      '✅ Dashboard familiar compartido',
    vip_familia_f4:      '✅ Soporte prioritario',
    get_vip_familia:     '👨‍👩‍👧 Obtener VIP Familia',
    legal_back_btn:      '← Volver',
    modal_upgrade_title: 'Mejora Tu Plan',
    btn_monthly:         'Mensual',
    btn_annual:          'Anual',
    btn_annual_save:     'Ahorra 17%',
    tab_stripe:          '💳 Tarjeta (Stripe)',
    tab_paypal:          '🅿️ PayPal',
    modal_secure:        '🔒 Seguro • Cancela cuando quieras • Sin cargos ocultos',
    feat_unlimited_tx:  'Transacciones ilimitadas',
    feat_basic_reports: 'Reportes básicos',
    feat_all_pro:       'Todo lo de Pro',
    feat_5_users:       'Hasta 5 usuarios',
    feat_admin_panel:   'Panel de administración',
    feat_biz_reports:   'Reportes empresariales',
    feat_support_247:   'Soporte prioritario 24/7',
    lbl_login_pass:     'Contraseña',
    lbl_reg_name:       'Nombre Completo',
    lbl_reg_plan:       'Plan',
    nav_admin_label:    'Admin Panel',
    scan_tip_1:         'Asegúrate de que el recibo esté completamente visible',
    scan_tip_2:         'Buena iluminación para mejor reconocimiento',
    scan_tip_3:         'Mantén el teléfono estable al fotografiar',
    scan_tip_4:         'Funciona con recibos en inglés y español',
    plan_pro_name:       '💎 Pro',
    plan_pro_real_price: 'Valor real $39.99/mes',
    pro_f1:              '✅ <strong>IA ilimitada 24/7</strong>',
    pro_f2:              '✅ <strong>GPT-4o</strong> — la IA más avanzada',
    pro_f3:              '✅ Transacciones ilimitadas · Hasta 10 tarjetas',
    pro_f4:              '✅ Scanner inteligente de recibos',
    pro_f5:              '✅ Reportes avanzados con insights',
    pro_f6:              '✅ Metas financieras con IA',
    pro_f7:              '✅ <strong>Ahorra $340/mes en promedio</strong>',
    cta_pro_label:       '⚡ Quiero ahorrar $340/mes — ',
    pro_cancel_note:     '✅ Cancela cuando quieras · Pago 100% seguro',
    plan_business_name:  '🏢 Business',
    biz_f1:              '✅ Todo lo de Pro',
    biz_f2:              '✅ Hasta 5 usuarios',
    biz_f3:              '✅ Gestión de equipo',
    biz_f4:              '✅ Reportes empresariales',
    biz_f5:              '✅ Soporte prioritario 24/7',
    biz_f6:              '✅ API Access para integraciones',
    biz_f7:              '✅ Tarjetas y usuarios ilimitados',
    biz_f8:              '✅ <strong>ROI garantizado o devolvemos tu dinero</strong>',
    cta_business_label:  '🏢 Potencia tu negocio — ',
    testimonial_quote:   '"Recuperé $180 el primer mes detectando suscripciones olvidadas y gastos innecesarios"',
    testimonial_author:  '— María G., usuaria Pro desde 2024',
    vip_code_label:      '¿Tienes un código VIP?',
    notif_label_1:       'Alertas de suscripciones',
    notif_label_2:       'Gastos inusuales',
    notif_label_3:       'Resumen semanal',
    current_plan_label:   '✨ Tu plan actual: FREE',
    pricing_tagline:      'Invierte menos que un café al día y recupera cientos al mes',
    plan_free_name:       '🆓 Free',
    plan_free_period:     '/mes',
    modal_free_f5:        '❌ Sin reportes avanzados',
    modal_free_f6:        '❌ Sin GPT-4o',
    btn_free_label:       'Gratis para siempre',
    billing_monthly:      'Mensual',
    billing_annual:       'Anual',
    annual_savings_text:  '🎉 Pagas anual y ahorras hasta <strong>$120/año</strong> — 2 meses GRATIS',
    plan_personal_name:   '⭐ Personal',
    modal_personal_f1:    '✅ Transacciones ilimitadas',
    modal_personal_f2:    '✅ Reportes básicos',
    modal_personal_f3:    '❌ Sin GPT-4o',
    cta_personal_label:   '🚀 Empezar ahora — Solo ',
    sub_scanner:       'Take a photo of your receipt and AI detects everything automatically',
    sub_cards:         'Manage your credit and debit cards',
    title_rec_ia:      '💡 AI Recommendations',
    sub_subs:          'Manage all your active subscriptions',
    debt_rec_ia_label: '💡 AI Recommendation:',
    title_card_recs:   '⭐ Card Recommendations',
    sub_card_recs:     'The best cards according to your spending habits',
    ai_cap_1:          '• 📊 Analyze your expenses and income',
    pf3:             '50 AI messages per day',
    pf4:             'Up to 3 cards',
    pf5:             'Receipt Scanner',
    modal_free_f1:   '✅ 5 AI messages per day',
    modal_free_f2:   '✅ Up to 30 transactions',
    modal_free_f3:   '✅ 1 card',
    modal_free_f4:   '❌ No receipt scanner',
    modal_pro_f1:    '✅ 50 AI messages per day',
    modal_pro_f2:    '✅ Up to 3 cards',
    modal_pro_f3:    '✅ Receipt Scanner',
    upgrade_li_scanner: '✅ Receipt Scanner',
    pf1:             'Up to 50 transactions/month',
    pf2:             '1 credit card',
    ai_msgs_today:   '5/5 messages today',

    // APP.HTML data-key mappings
    dash_dashboard:      'Dashboard',
    dash_receipts:       'Receipt Scanner',
    dash_transactions:   'Transactions',
    dash_cards:          'My Cards',
    dash_debt:           'Debt Plan',
    dash_subscriptions:  'Subscriptions',
    dash_ai:             'AI Assistant',
    dash_settings:       'Settings',
    dash_welcome:        'Welcome back',
    dash_scan:           'Scan Receipt',
    dash_income:         'Monthly Income',
    dash_expenses:       'Monthly Expenses',
    dash_balance:        'Total Balance',
    dash_savings:        'Savings Rate',
    dash_recent:         'Recent Transactions',
    dash_quick:          'Quick Actions',
    dash_add:            'Add Transaction',
    dash_plan:           'View Debt Plan',
    dash_recommend:      'Card Recommendations',
    scan_result:         'Detected Expense',
    scan_type:           'Type',
    scan_rescan:         'Scan Another',
    cards_recommend:     'Best Card For...',
    debt_title:          'Debt Payoff Plan',
    debt_add:            'Add Debt',
    debt_monthly:        'Monthly Payment',
    debt_payoff:         'Est. Payoff',
    debt_interest:       'Interest Saved',
    debt_method:         'Payoff Method',
    debt_avalanche:      'Avalanche (Highest Interest First)',
    debt_snowball:       'Snowball (Smallest Balance First)',
    debt_name:           'Debt Name',
    debt_balance:        'Balance',
    debt_min:            'Min. Payment',
    debt_rate:           'Interest Rate',
    debt_save:           'Save Debt',
    subs_next:           'Next Charge',
    ai_title:            'AI Assistant',
    ai_suggestions:      'Try asking:',
    settings_title:      'Settings',
    settings_profile:    'Profile',
    settings_currency:   'Currency',
    settings_language:   'Language',
    settings_plan:       'Current Plan',
    settings_upgrade:    'Upgrade Plan',
    settings_save:       'Save Changes',
    settings_notifications: 'Notifications',

    // DYNAMIC MESSAGES
    upgrade_available:      'Available from plan',
    upgrade_warning:        '🚨 Only {n} transactions left — upgrade now!',
    ai_limit_reached:       '🔒 You have reached your 5 messages/day limit. Upgrade to VIP for unlimited messages! 🌟',
    ai_limit_daily:         '🔒 Daily limit reached. Upgrade to VIP! 🌟',
    ai_msgs_day:            '5 AI messages per day',
    ai_msgs_warning:        '⚠️ {n} AI messages left today — consider upgrading',
    trans_empty_cat:        'No transactions in this category.',
    trans_export_empty:     'No transactions to export yet — add some!',
    export_filename:        'financeai_transactions',
    credit_limit:           'Credit limit',

    // TOASTS & DYNAMIC UI
    subs_invalid_amount:    'Enter a valid amount',
    subs_save_error:        'Error saving subscription',
    subs_deleted:           'Subscription deleted',
    subs_delete_error:      'Error deleting subscription',
    plan_vip_sub:           'Unlimited messages · Expires in {n} days',
    plan_free:              'Free',
    plan_free_forever:      'Free forever',
    plan_current:           'Your current plan',
    plan_current_free:      'Your current plan — Free',
    plan_expires:           'Expires in {n} days',
    plan_actual:            'Current plan:',
    scan_requires_plan:     'Scanner requires Personal plan or higher',
    scan_unknown:           'Unknown',
    scan_other:             'Other',
    scan_error:             'Error analyzing receipt. Try another image.',
    scan_no_data:           'No receipt data to save',
    scan_save_error:        'Error saving transaction',
    scan_read_error:        'Could not read receipt — try with better lighting 📸',
    scan_first:             'Scan a receipt first 📸',
    scan_save_error2:       'Error saving — try again in a moment',
    pdf_ready:              '✅ PDF ready — use "Save as PDF" in the print dialog 🎉',
    card_name_required:     'Enter the cardholder name',
    card_save_error:        'Error saving card',
  },

  es: {
    // NAVBAR
    nav_features:    'Funciones',
    nav_pricing:     'Precios',
    nav_login:       'Entrar',
    nav_start:       'Empezar Gratis',

    // HERO
    hero_badge:      '✨ POWERED BY AI — GRATIS PARA EMPEZAR',
    hero_title:      'Toma el Control de tus <span style="color:#00EEFF">Finanzas</span> con Inteligencia Artificial',
    hero_desc:       'Escanea recibos, gestiona deudas, descubre las mejores tarjetas y recibe recomendaciones personalizadas con IA. Todo en un solo lugar.',
    hero_cta:        '🚀 Empezar Gratis Ahora',
    hero_demo:       'Ver Demo',
    stat1:           'Usuarios Activos',
    stat2:           'En Deudas Gestionadas',
    stat3:           'Tarjetas Compatibles',
    stat4:           'Calificación Promedio',

    // FEATURES SECTION
    feat_title:      'Todo lo que necesitas para tus finanzas',
    feat_sub:        'Funciones poderosas impulsadas por inteligencia artificial',
    f1_title:        'Escáner de Recibos IA',
    f1_desc:         'Fotografía cualquier recibo y nuestra IA detecta automáticamente el monto, categoría, fecha y comercio.',
    f2_title:        'Mejor Tarjeta para Cada Gasto',
    f2_desc:         'Recibe recomendaciones de qué tarjeta usar según los beneficios, cashback y puntos disponibles.',
    f3_title:        'Plan de Pago de Deudas',
    f3_desc:         'Estrategias personalizadas para pagar tus deudas más rápido usando los métodos Avalanche y Snowball.',
    f4_title:        'Asistente Financiero IA',
    f4_desc:         'Pregunta cualquier cosa sobre tus finanzas y recibe consejos personalizados basados en tus datos reales.',
    f5_title:        'Gestión de Suscripciones',
    f5_desc:         'Detecta automáticamente tus suscripciones activas, te alerta antes de cobros y calcula cuánto gastas al mes.',
    f6_title:        'Personal vs Empresa',
    f6_desc:         'Separa automáticamente gastos personales de los del negocio para mantener tus finanzas organizadas.',

    // PRICING SECTION
    price_title:     'Planes y Precios',
    price_sub:       'Comienza gratis, escala cuando estés listo',
    billing_monthly: 'Mensual',
    billing_annual:  'Anual',
    billing_save:    '-20%',
    billing_banner:  '🎉 Pagas anual y ahorras hasta $120/año — 2 meses GRATIS',
    plan_popular:    'Más Popular',
    plan_current:    'Tu plan actual',
    plan_month:      '/mes',
    plan_year:       '/año',
    period_personal: '/mes',
    period_pro:      '/mes',
    period_business: '/mes',
    plan_free_btn:   'Gratis para siempre',
    plan_pers_btn:   'Obtener Personal',
    plan_pro_btn:    'Obtener Pro',
    plan_biz_btn:    'Obtener Business',

    // SIDEBAR NAV
    nav_dash:         'Dashboard',
    dash_limit_reached: 'Límite alcanzado:',
    dash_upgrade:       'Actualiza tu plan',
    dash_txs_used:      'transacciones usadas',
    dash_consider_upgrade: 'Considera actualizar tu plan',
    tx_empty:    'No tienes transacciones registradas.',
    tx_no_desc:  'Sin descripción',
    nav_scan:        'Escáner IA',
    nav_trans:       'Transacciones',
    nav_cards:       'Mis Tarjetas',
    nav_debts:       'Deudas',
    nav_subs:        'Suscripciones',
    nav_recs:        'Recomendaciones',
    nav_ai:          'Asistente IA',
    nav_rep:         'Reportes',
    nav_set:         'Configuración',
    nav_logout:      'Cerrar Sesión',

    // DASHBOARD
    dash_title:      'Dashboard',
    dash_sub:        'Resumen financiero de este mes',
    lbl_income:      'Ingresos del Mes',
    lbl_expense:     'Gastos del Mes',
    lbl_balance:     'Balance Disponible',
    lbl_debt:        'Deuda Total',
    lbl_recent:      'Transacciones Recientes',
    lbl_subs:        'Suscripciones Activas',
    lbl_debts:       'Plan de Deudas',
    dash_view_all:   'Ver todas',
    dash_ai_title:   '🤖 Asistente IA',
    dash_ai_online:  'En línea',
    dash_chat_ph:    'Pregúntame algo sobre tus finanzas...',
    dash_vs_last:        '↑ % vs mes anterior',
    dash_healthy:        '✓ Finanzas saludables',
    dash_debt_month:     '↓ este mes',
    dash_messages_left:  'mensajes hoy',

    // TRANSACTIONS
    trans_title:     'Transacciones',
    trans_add:       'Agregar Transacción',
    trans_all:       'Todas',
    trans_income:    'Ingresos',
    trans_expense:   'Gastos',
    trans_empty:     'Sin transacciones aún',

    // CARDS
    cards_title:     'Mis Tarjetas',
    cards_add:       'Agregar Tarjeta',
    card_healthy:     'Saludable',
    card_warning:     'Precaución',
    card_danger:      'Alto uso',
    card_holder:      'TITULAR',
    card_limit_label: 'LÍMITE',
    card_no_name:     'Sin nombre',
    card_due:         'Vence día',
    cards_personal:   '👤 Tarjetas Personales',
    cards_business:   '🏢 Tarjetas de Empresa',
    card_edit_title:  '✏️ Editar Tarjeta',
    card_name_bank:   'Nombre / Banco',
    card_type_label:  'Tipo',
    card_limit_lbl:   'Límite ($)',
    card_balance_lbl: 'Balance usado ($)',
    card_last4:       'Últimos 4 dígitos',
    card_apr:         'APR (%)',
    card_color:       'Color de tarjeta',
    card_due_day:     'Día de vencimiento',
    card_name_required: 'El nombre es requerido',
    card_updated:     '✅ Tarjeta actualizada',
    card_save_error:  'Error al guardar cambios',
    card_deleted:     'Tarjeta eliminada',
    card_delete_error:'Error al eliminar tarjeta',
    btn_cancel:       'Cancelar',
    btn_save:         '💾 Guardar Cambios',
    debt_add_title:    '📉 Agregar Deuda',
    debt_name_label:      'Nombre (Tarjeta / Préstamo)',
    debt_name_placeholder:'ej: Chase Visa...',
    debt_balance_label:   'Balance Actual ($)',
    debt_min_label:       'Pago Mínimo Mensual ($)',
    debt_save_btn:        '💾 Guardar Deuda',
    debt_invalid_balance: 'Ingresa un balance válido',
    session_expired:      'Sesión expirada',
    debt_added:           '✅ Deuda agregada!',
    debt_save_error:      'Error al guardar deuda',
    debt_deleted:         'Deuda eliminada',
    debt_delete_error:    'Error al eliminar deuda',
    debts_empty:          'No tienes deudas registradas.',
    debt_priority_high:   'Prioridad ALTA',
    debt_priority_med:    'Prioridad MEDIA',
    debt_priority_low:    'Pago mínimo por ahora',
    debt_used:            'usado',
    debt_of:              'de',
    debt_utilized:        'utilizado',
    debt_min_pay:         'Pago mínimo',
    btn_delete:           'Eliminar',
    debts_personal:       'Deudas Personales',
    debts_business:       'Deudas Empresa',
    time_years:           'años',
    time_months:          'meses',
    method_avalanche:     '❄️ Método Avalanche',
    method_snowball:      '⛄ Método Snowball',
    toast_avalanche:      '📊 Avalanche: ¡Pagas menos intereses en total!',
    toast_snowball:       '⛄ Snowball: ¡Más motivación para seguir!',
    cards_limit:     'Límite de Crédito',
    cards_used:      'Usado',
    cards_available: 'Disponible',
    cards_empty:     'No hay tarjetas agregadas',

    // DEBTS
    debts_title:     'Deudas',
    debts_total:     'Deuda Total',
    debts_payoff:    'Liquidación Estimada',
    debts_method:    'Método de Pago',
    debts_add:       'Agregar Deuda',
    debt_method_title: '❄️ Método Avalanche',
    debt_ai_recs:    '💡 Recomendaciones IA',

    // SUBSCRIPTIONS
    subs_title:      'Suscripciones',
    subs_total:      'Total Mensual',
    subs_count:      'Suscripciones Activas',
    subs_add:        'Agregar Suscripción',
    subs_empty:      'Sin suscripciones aún',

    // SCANNER
    scan_title:      'Escáner de Recibos IA',
    scan_upload:     'Arrastra tu recibo aquí o haz clic para subir',
    scan_formats:    'Soporta JPG, PNG, PDF',
    scan_analyzing:  'Analizando recibo...',
    scan_merchant:   'Comercio',
    scan_amount:     'Monto',
    scan_date:       'Fecha',
    scan_category:   'Categoría',
    scan_save:       'Guardar Gasto',

    // REPORTS
    rep_title:       'Reportes',
    rep_cat:         '📊 Gastos por Categoría',
    rep_monthly:     '📅 Resumen Mensual 2025',

    // SETTINGS
    set_title:       'Configuración',
    set_profile:     '👤 Perfil',
    set_subtitle:    'Personaliza tu experiencia',
    lbl_name:        'Nombre',
    lbl_email:       'Email',
    lbl_country:     'País',
    set_currency:    'Moneda',
    set_language:    '🌐 Idioma',
    set_plan:        '💳 Elige tu plan',
    set_notif:       '🔔 Notificaciones',
    set_danger:      '⚠️ Zona de Peligro',
    set_legal:       '⚖️ Legal',
    set_save:        'Guardar Cambios',
    set_logout_all:  'Cerrar Sesión en Todos los Dispositivos',
    set_delete:      'Eliminar Cuenta',

    // GENERAL
    general_save:    'Guardar',
    general_cancel:  'Cancelar',
    general_delete:  'Eliminar',
    general_edit:    'Editar',
    general_add:     'Agregar',
    general_close:   'Cerrar',
    general_loading: 'Cargando...',
    general_yes:     'Sí, eliminar',
    general_personal:'Personal',
    general_business:'Empresa',

    // TOASTS
    toast_saved:     'Guardado exitosamente',
    toast_deleted:   'Eliminado exitosamente',
    toast_error:     'Error. Por favor intenta de nuevo.',

    // UPGRADE MODAL
    upgrade_title:   'Actualiza tu plan',
    upgrade_cta:     'Ver Planes',
    upgrade_cancel:  'Quizás después',

    // LIMIT BANNERS
    limit_reached:   '🚫 Límite alcanzado',
    limit_warning:   '⚠️ usadas — Considera actualizar',
    limit_upgrade:   'Actualiza tu plan',

    // AI CHAT
    ai_welcome:      '👋 ¡Hola! Soy tu asistente financiero IA. ¿En qué te puedo ayudar?',
    ai_placeholder:  'Pregúntame algo sobre tus finanzas...',
    ai_thinking:     '💭 Pensando...',
    ai_msgs_left:    'mensajes hoy',
    debt_tip_text:       'Paga primero la tarjeta con mayor tasa de interés.',
    credit_score_warn:   'Tu score crediticio puede bajar. Prioriza reducir esta tarjeta primero.',
    badge_vence_pronto:  'Vence pronto',
    rec_based_on:        'Basado en tus transacciones: gastas más en ',
    rec_desc_default:    'Disponible en México, Colombia y Brasil. Sin cuotas ocultas, control total desde el app.',
    no_trans_yet:        'Sin transacciones aún',
    sub_scanner:       'Fotografía tu recibo y la IA detecta todo automáticamente',
    sub_cards:         'Gestiona tus tarjetas de crédito y débito',
    title_rec_ia:      '💡 Recomendaciones IA',
    sub_subs:          'Gestiona todas tus suscripciones activas',
    debt_rec_ia_label: '💡 Recomendación IA:',
    title_card_recs:   '⭐ Recomendaciones de Tarjetas',
    sub_card_recs:     'Las mejores tarjetas según tus hábitos de gasto',
    ai_cap_1:          '• 📊 Analizar tus gastos e ingresos',
    pf3:             '50 mensajes IA por día',
    pf4:             'Hasta 3 tarjetas',
    pf5:             'Scanner de recibos',
    modal_free_f1:   '✅ 5 mensajes IA por día',
    modal_free_f2:   '✅ Hasta 30 transacciones',
    modal_free_f3:   '✅ 1 tarjeta',
    modal_free_f4:   '❌ Sin scanner de recibos',
    modal_pro_f1:    '✅ 50 mensajes IA por día',
    modal_pro_f2:    '✅ Hasta 3 tarjetas',
    modal_pro_f3:    '✅ Scanner de recibos',
    upgrade_li_scanner: '✅ Scanner de recibos',
    pf1:             'Hasta 50 transacciones/mes',
    pf2:             '1 tarjeta de crédito',
    ai_msgs_today:   '5/5 mensajes hoy',

    // APP.HTML data-key mappings
    dash_dashboard:      'Dashboard',
    dash_receipts:       'Escáner de Recibos',
    dash_transactions:   'Transacciones',
    dash_cards:          'Mis Tarjetas',
    dash_debt:           'Plan de Deudas',
    dash_subscriptions:  'Suscripciones',
    dash_ai:             'Asistente IA',
    dash_settings:       'Configuración',
    dash_welcome:        'Bienvenido de vuelta',
    dash_scan:           'Escanear Recibo',
    dash_income:         'Ingresos del Mes',
    dash_expenses:       'Gastos del Mes',
    dash_balance:        'Balance Total',
    dash_savings:        'Tasa de Ahorro',
    dash_recent:         'Transacciones Recientes',
    dash_quick:          'Acciones Rápidas',
    dash_add:            'Agregar Transacción',
    dash_plan:           'Ver Plan de Deudas',
    dash_recommend:      'Recomendaciones de Tarjetas',
    scan_result:         'Gasto Detectado',
    scan_type:           'Tipo',
    scan_rescan:         'Escanear Otro',
    cards_recommend:     'Mejor Tarjeta Para...',
    debt_title:          'Plan de Pago de Deudas',
    debt_add:            'Agregar Deuda',
    debt_monthly:        'Pago Mensual',
    debt_payoff:         'Liquidación Est.',
    debt_interest:       'Interés Ahorrado',
    debt_method:         'Método de Pago',
    debt_avalanche:      'Avalanche (Mayor Interés Primero)',
    debt_snowball:       'Snowball (Menor Balance Primero)',
    debt_name:           'Nombre de Deuda',
    debt_balance:        'Balance',
    debt_min:            'Pago Mínimo',
    debt_rate:           'Tasa de Interés',
    debt_save:           'Guardar Deuda',
    subs_next:           'Próximo Cobro',
    ai_title:            'Asistente IA',
    ai_suggestions:      'Intenta preguntar:',
    settings_title:      'Configuración',
    settings_profile:    'Perfil',
    settings_currency:   'Moneda',
    settings_language:   'Idioma',
    settings_plan:       'Plan Actual',
    settings_upgrade:    'Actualizar Plan',
    settings_save:       'Guardar Cambios',
    settings_notifications: 'Notificaciones',

    // DYNAMIC MESSAGES
    upgrade_available:      'Disponible desde el plan',
    upgrade_warning:        '🚨 Solo te quedan {n} transacciones — ¡Actualiza ahora!',
    ai_limit_reached:       '🔒 Alcanzaste tu límite de 5 mensajes hoy. ¡Actualiza a VIP para mensajes ilimitados! 🌟',
    ai_limit_daily:         '🔒 Límite diario alcanzado. ¡Actualiza a VIP! 🌟',
    ai_msgs_day:            '5 mensajes IA por día',
    ai_msgs_warning:        '⚠️ Te quedan {n} mensajes IA hoy — considera actualizar tu plan',
    trans_empty_cat:        'No tienes transacciones en esta categoría.',
    trans_export_empty:     'No hay transacciones para exportar aún — ¡agrega algunas!',
    export_filename:        'financeai_transacciones',
    credit_limit:           'Límite de crédito',

    // TOASTS & DYNAMIC UI
    subs_invalid_amount:    'Ingresa un monto válido',
    subs_save_error:        'Error al guardar suscripción',
    subs_deleted:           'Suscripción eliminada',
    subs_delete_error:      'Error al eliminar suscripción',
    plan_vip_sub:           'Mensajes ilimitados · Vence en {n} días',
    plan_free:              'Gratuito',
    plan_free_forever:      'Gratis para siempre',
    plan_current:           'Tu plan actual',
    plan_current_free:      'Tu plan actual — Gratis',
    plan_expires:           'Vence en {n} días',
    plan_actual:            'Plan actual:',
    scan_requires_plan:     'El Scanner requiere plan Personal o superior',
    scan_unknown:           'Desconocido',
    scan_other:             'Otro',
    scan_error:             'Error al analizar el recibo. Intenta con otra imagen.',
    scan_no_data:           'No hay datos del recibo para guardar',
    scan_save_error:        'Error al guardar la transacción',
    scan_read_error:        'No pudimos leer ese recibo — intenta con mejor iluminación 📸',
    scan_first:             'Escanea un recibo primero para guardarlo 📸',
    scan_save_error2:       'Error al guardar — intenta de nuevo en un momento',
    pdf_ready:              '✅ PDF listo — usa "Guardar como PDF" en el diálogo de impresión 🎉',
    card_name_required:     'Ingresa el nombre del titular',
    card_save_error:        'Error al guardar tarjeta',
  }
};

// ===========================
// ID → KEY MAP (complete)
// ===========================
const ID_KEY_MAP = {
  // NAVBAR
  'nav-features':      'nav_features',
  'nav-pricing':       'nav_pricing',
  'nav-login':         'nav_login',
  'nav-start':         'nav_start',

  // HERO
  'hero-badge':        'hero_badge',
  'hero-title':        'hero_title',
  'hero-desc':         'hero_desc',
  'hero-cta':          'hero_cta',
  'hero-demo':         'hero_demo',
  'stat1':             'stat1',
  'stat2':             'stat2',
  'stat3':             'stat3',
  'stat4':             'stat4',

  // FEATURES
  'feat-title':        'feat_title',
  'feat-sub':          'feat_sub',
  'f1-title':          'f1_title',
  'f1-desc':           'f1_desc',
  'f2-title':          'f2_title',
  'f2-desc':           'f2_desc',
  'f3-title':          'f3_title',
  'f3-desc':           'f3_desc',
  'f4-title':          'f4_title',
  'f4-desc':           'f4_desc',
  'f5-title':          'f5_title',
  'f5-desc':           'f5_desc',
  'f6-title':          'f6_title',
  'f6-desc':           'f6_desc',

  // PRICING
  'price-title':       'price_title',
  'price-sub':         'price_sub',
  'period-personal':   'period_personal',
  'period-pro':        'period_pro',
  'period-business':   'period_business',

  // SIDEBAR NAV
  'nav-dash':          'nav_dash',
  'nav-scan':          'nav_scan',
  'nav-trans':         'nav_trans',
  'nav-cards':         'nav_cards',
  'nav-debts':         'nav_debts',
  'nav-subs':          'nav_subs',
  'nav-recs':          'nav_recs',
  'nav-ai':            'nav_ai',
  'nav-rep':           'nav_rep',
  'nav-set':           'nav_set',

  // DASHBOARD
  'dash-title':        'dash_title',
  'dash-sub':          'dash_sub',
  'lbl-income':        'lbl_income',
  'lbl-expense':       'lbl_expense',
  'lbl-balance':       'lbl_balance',
  'pf1':               'pf1',
  'pf2':               'pf2',
  'aiMessagesLeft':    'ai_msgs_today',
  'debt-tip-text':      'debt_tip_text',
  'credit-score-warn':  'credit_score_warn',
  'badge-vence-pronto': 'badge_vence_pronto',
  'rec-based-on':       'rec_based_on',
  'rec-desc-default':   'rec_desc_default',
  'no-trans-yet':       'no_trans_yet',
  'pf3':               'pf3',
  'pf4':               'pf4',
  'pf5':               'pf5',
  'modal-free-f1':     'modal_free_f1',
  'modal-free-f2':     'modal_free_f2',
  'modal-free-f3':     'modal_free_f3',
  'modal-free-f4':     'modal_free_f4',
  'modal-pro-f1':      'modal_pro_f1',
  'modal-pro-f2':      'modal_pro_f2',
  'modal-pro-f3':      'modal_pro_f3',
  'upgrade-li-scanner':'upgrade_li_scanner',
  'sub-scanner':       'sub_scanner',
  'sub-cards':         'sub_cards',
  'title-rec-ia':      'title_rec_ia',
  'sub-subs':          'sub_subs',
  'debt-rec-ia-label': 'debt_rec_ia_label',
  'title-card-recs':   'title_card_recs',
  'sub-card-recs':     'sub_card_recs',
  'ai-cap-1':          'ai_cap_1',
  'current-plan-label':  'current_plan_label',
  'pricing-tagline':     'pricing_tagline',
  'plan-free-name':      'plan_free_name',
  'plan-free-period':    'plan_free_period',
  'modal-free-f5':       'modal_free_f5',
  'modal-free-f6':       'modal_free_f6',
  'btn-free-label':      'btn_free_label',
  'billing-monthly-label': 'billing_monthly',
  'billing-annual-label':  'billing_annual',
  'annual-savings-text': 'annual_savings_text',
  'plan-personal-name':  'plan_personal_name',
  'modal-personal-f1':   'modal_personal_f1',
  'modal-personal-f2':   'modal_personal_f2',
  'modal-personal-f3':   'modal_personal_f3',
  'cta-personal-label':  'cta_personal_label',
  'badge-popular':       'badge_popular',
  'notif-label-4':       'notif_label_4',
  'danger-zone-title':   'danger_zone_title',
  'delete-account-btn-label': 'delete_account_btn',
  'legal-title':         'legal_title',
  'legal-terms-title':   'legal_terms_title',
  'legal-terms-desc':    'legal_terms_desc',
  'legal-privacy-title': 'legal_privacy_title',
  'legal-privacy-desc':  'legal_privacy_desc',
  'copyright-text':      'copyright_text',
  'admin-page-title':    'admin_page_title',
  'admin-page-subtitle': 'admin_page_subtitle',
  'admin-label-total-users': 'admin_label_total',
  'admin-label-vip-users':   'admin_label_vip',
  'admin-label-codes':         'admin_label_codes',
  'admin-label-ai-calls':      'admin_label_ai_calls',
  'admin-vip-mgmt-title':      'admin_vip_mgmt_title',
  'admin-gen-code-label':      'admin_gen_code_label',
  'admin-opt-personal':        'admin_opt_personal',
  'admin-opt-familia':         'admin_opt_familia',
  'admin-opt-1m':              'admin_opt_1m',
  'admin-opt-3m':              'admin_opt_3m',
  'admin-opt-6m':              'admin_opt_6m',
  'admin-opt-12m':             'admin_opt_12m',
  'admin-gen-code-btn-label':  'admin_gen_code_btn',
  'admin-code-generated-label':'admin_code_generated',
  'admin-copy-btn-label':      'admin_copy_btn',
  'admin-session-codes-label': 'admin_session_codes',
  'admin-no-codes-msg':        'admin_no_codes_msg',
  'admin-used-codes-title':    'admin_used_codes_title',
  'admin-loading-msg':         'admin_loading_msg',
  'admin-activate-vip-title':  'admin_activate_vip',
  'vip-status-sub-text':       'vip_status_sub_text',
  'admin-vip-enter-label':     'admin_vip_enter_label',
  'activate-vip-btn-label':    'activate_vip_btn',
  'or-buy-plan-label':         'or_buy_plan',
  'vip-personal-name':         'vip_personal_name',
  'vip-personal-badge':        'vip_personal_badge',
  'vip-personal-f1':           'vip_personal_f1',
  'vip-personal-f2':           'vip_personal_f2',
  'vip-personal-f4':           'vip_personal_f4',
  'get-vip-personal-btn':      'get_vip_personal',
  'vip-familia-name':          'vip_familia_name',
  'vip-familia-f1':            'vip_familia_f1',
  'vip-familia-f2':            'vip_familia_f2',
  'vip-familia-f3':            'vip_familia_f3',
  'vip-familia-f4':            'vip_familia_f4',
  'get-vip-familia-btn':       'get_vip_familia',
  'legal-back-btn':            'legal_back_btn',
  'modal-upgrade-title':       'modal_upgrade_title',
  'btn-monthly-label':         'btn_monthly',
  'btn-annual-label':          'btn_annual',
  'btn-annual-save':           'btn_annual_save',
  'tab-stripe-label':          'tab_stripe',
  'tab-paypal-label':          'tab_paypal',
  'modal-secure-text':         'modal_secure',
  'feat-unlimited-tx':         'feat_unlimited_tx',
  'feat-basic-reports':        'feat_basic_reports',
  'feat-all-pro':              'feat_all_pro',
  'feat-5-users':              'feat_5_users',
  'feat-admin-panel':          'feat_admin_panel',
  'feat-biz-reports':          'feat_biz_reports',
  'feat-support-247':          'feat_support_247',
  'lbl-login-pass':            'lbl_login_pass',
  'lbl-reg-name':              'lbl_reg_name',
  'lbl-reg-plan':              'lbl_reg_plan',
  'nav-admin-label':           'nav_admin_label',
  'scan-tip-1':                'scan_tip_1',
  'scan-tip-2':                'scan_tip_2',
  'scan-tip-3':                'scan_tip_3',
  'scan-tip-4':                'scan_tip_4',
  'plan-pro-name':       'plan_pro_name',
  'plan-pro-real-price': 'plan_pro_real_price',
  'pro-f1':              'pro_f1',
  'pro-f2':              'pro_f2',
  'pro-f3':              'pro_f3',
  'pro-f4':              'pro_f4',
  'pro-f5':              'pro_f5',
  'pro-f6':              'pro_f6',
  'pro-f7':              'pro_f7',
  'cta-pro-label':       'cta_pro_label',
  'pro-cancel-note':     'pro_cancel_note',
  'plan-business-name':  'plan_business_name',
  'biz-f1':              'biz_f1',
  'biz-f2':              'biz_f2',
  'biz-f3':              'biz_f3',
  'biz-f4':              'biz_f4',
  'biz-f5':              'biz_f5',
  'biz-f6':              'biz_f6',
  'biz-f7':              'biz_f7',
  'biz-f8':              'biz_f8',
  'cta-business-label':  'cta_business_label',
  'testimonial-quote':   'testimonial_quote',
  'testimonial-author':  'testimonial_author',
  'vip-code-label':      'vip_code_label',
  'notif-label-1':       'notif_label_1',
  'notif-label-2':       'notif_label_2',
  'notif-label-3':       'notif_label_3',
  'vip-status-sub':    'ai_msgs_day',
  'lbl-debt':          'lbl_debt',
  'lbl-recent':        'lbl_recent',
  'lbl-subs':          'lbl_subs',
  'lbl-debts':         'lbl_debts',
  'debt-method-title': 'debt_method_title',
};

// ===========================
// LANGUAGE STATE
// ===========================
let currentLang = localStorage.getItem('financeai_lang') || 'es';

// ===========================
// t() — get translation
// ===========================
function t(key) {
  return (TRANSLATIONS[currentLang] && TRANSLATIONS[currentLang][key])
    || (TRANSLATIONS['en'] && TRANSLATIONS['en'][key])
    || key;
}

// ===========================
// applyLanguage — full DOM
// ===========================
function applyLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('financeai_lang', lang);
  document.documentElement.lang = lang;

  // 1. ID_KEY_MAP
  Object.entries(ID_KEY_MAP).forEach(([id, key]) => {
    const el = document.getElementById(id);
    if (el) el.innerHTML = t(key);
  });

  // 2. data-i18n attributes
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (key) el.innerHTML = t(key);
  });

  // 2b. data-key attributes (legacy support)
  document.querySelectorAll('[data-key]').forEach(el => {
    const key = el.getAttribute('data-key');
    if (key) el.innerHTML = t(key);
  });

  // 3. data-i18n-placeholder
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (key) el.placeholder = t(key);
  });

  // 4. Logout buttons
  document.querySelectorAll('[data-i18n-logout]').forEach(btn => {
    btn.textContent = t('nav_logout');
  });

  // 5. Lang button active state
  document.querySelectorAll('.lang-btn').forEach(btn => {
    const onclick = btn.getAttribute('onclick') || '';
    btn.classList.toggle('active', onclick.includes(`'${lang}'`));
  });

  // 6. Dispatch event for app.js dynamic content
  window.dispatchEvent(new CustomEvent('langChanged', { detail: { lang } }));
}

// ===========================
// setLang — public API
// ===========================
function setLang(lang) {
  applyLanguage(lang);
}

// ===========================
// toggleLang
// ===========================
function toggleLang() {
  setLang(currentLang === 'en' ? 'es' : 'en');
}

// ===========================
// INIT
// ===========================
document.addEventListener('DOMContentLoaded', () => {
  applyLanguage(currentLang);
});

// ===========================
// EXPORTS
// ===========================
window.t = t;
window.setLang = setLang;
window.toggleLang = toggleLang;
window.FinanceAILang = {
  toggle: toggleLang,
  apply: applyLanguage,
  get: t,
  current: () => currentLang,
  translations: TRANSLATIONS
};
