// ===========================
// FINANCEAI PRO — LANG.JS
// i18n Architecture v2.0
// Climberforsuccess LLC
// ===========================

const TRANSLATIONS = {
  en: {
    // NAVBAR
    modal_title:     'Notice',
    landing_original_personal: 'Regular price $9.99/mo',
    landing_original_pro:      'Real value $39.99/mo',
    landing_original_business: 'Regular price $49.99/mo',
    pf3_dashboard:             'Basic dashboard',
    nav_features:    'Features',
    nav_pricing:     'Pricing',
    nav_login:       'Login',
    nav_start:       'Start Free',

    // HERO
    hero_badge:      '✨ POWERED BY AI — FREE TO START',
    hero_title:      'Take Control of your <span style="color:#00EEFF">Finances</span> with Artificial Intelligence',
    hero_desc:       'Scan receipts, manage debts, discover the best cards and get personalized AI recommendations. All in one place.',
    hero_cta:        '🚀 Start Free Now',
    hero_demo:       'Watch Demo',
    landing_btn_monthly: 'Monthly',
    landing_btn_annual:  'Annual',
    landing_savings_banner: '🎉 Annual payment = 2 months FREE — Save up to <strong>$120/year</strong>',
    stat1:           'Active Users',
    stat2:           'In Managed Debts',
    stat3:           'Compatible Cards',
    stat4:           'Average Rating',

    // FEATURES SECTION
    feat_title:      'Everything you need for your finances',
    feat_sub:        'Powerful features powered by artificial intelligence',
    f1_title:        'AI Receipt Scanner',
    f1_desc:         'Photograph any receipt and our AI automatically detects the amount, category, date and merchant.',
    f2_title:        'Best Card for Each Purchase',
    f2_desc:         'Get recommendations on which card to use based on benefits, cashback and available points.',
    f3_title:        'Debt Payoff Plan',
    f3_desc:         'Personalized strategies to pay off your debts faster using Avalanche and Snowball methods.',
    f4_title:        'AI Financial Assistant',
    f4_desc:         'Ask anything about your finances and get personalized advice based on your real data.',
    f5_title:        'Subscription Manager',
    f5_desc:         'Automatically detect your active subscriptions, alert you before charges and calculate monthly spend.',
    f6_title:        'Personal vs Business',
    f6_desc:         'Automatically separate personal and business expenses to keep your finances organized.',

    // PRICING SECTION
    price_title:     'Plans & Pricing',
    price_sub:       'Start free, scale when you are ready',
    billing_monthly: 'Monthly',
    billing_annual:       'Annual',
    status_active:        'Active',
    status_due_soon:      'Due soon',
    cat_other:            'Other',
    vip_welcome:          '🌟 Welcome to VIP',
    enjoy_benefits:       'Enjoy your benefits.',
    cancel_sub:           'Cancel',
    per_month:            '/mo',
    plan_free_label:      'Free',
    billing_save:    '-20%',
    billing_banner:  '🎉 Annual plan saves you up to $120/year — 2 months FREE',
    plan_popular:    'Most Popular',
    plan_current:    'Current plan',
    plan_month:      '/mo',
    plan_year:       '/yr',
    period_personal: '/mo',
    period_pro:      '/mo',
    period_business: '/mo',
    plan_free_btn:   'Free forever',
    btn_start_free:  'Start Free',
    btn_start_now:   '🚀 Start Now',
    btn_want_pro:    '⚡ I Want Pro',
    feat_unlimited_ai: '✅ Unlimited AI 24/7',
    feat_gpt4o:            '✅ GPT-4o AI Engine',
    feat_unlimited_cards:  '✅ Unlimited card recommendations',
    feat_smart_scanner:    '✅ Smart receipt scanner',
    feat_advanced_reports: '✅ Advanced financial reports',
    feat_ai_goals:         '✅ AI-powered financial goals',
    feat_save_avg:         '✅ Save 23% on average',
    billed_annually:       'Billed annually — save 20%',
    plan_pers_btn:   'Get Personal',
    plan_pro_btn:    'Get Pro',
    plan_biz_btn:    'Get Business',

    // SIDEBAR NAV
    nav_dash:         'Dashboard',
    dash_limit_reached: 'Limit reached:',
    dash_upgrade:       'Upgrade your plan',
    dash_txs_used:      'transactions used',
    dash_consider_upgrade: 'Consider upgrading',
    tx_empty:    'You have no transactions yet.',
    tx_no_desc:  'No description',
    nav_scan:        'AI Scanner',
    nav_trans:       'Transactions',
    nav_cards:       'My Cards',
    nav_debts:       'Debts',
    nav_subs:        'Subscriptions',
    nav_recs:        'Recommendations',
    nav_ai:          'AI Assistant',
    nav_rep:         'Reports',
    nav_set:         'Settings',
    nav_logout:      'Log Out',

    // DASHBOARD
    dash_title:      'Dashboard',
    dash_sub:        'Financial summary for this month',
    lbl_income:      'Monthly Income',
    lbl_expense:     'Monthly Expenses',
    lbl_balance:     'Available Balance',
    lbl_debt:        'Total Debt',
    lbl_recent:      'Recent Transactions',
    btn_logout:      'Log Out',
    btn_add:         '+ Add',
    btn_view_all:    'View All',

    lbl_subs:        'Active Subscriptions',
    ai_assistant:    '🤖 AI Assistant',
    badge_online:    'Online',
    dash_chat_intro: '👋 Hi! I am your AI financial assistant. This month you have spent <strong>$2,847.50</strong> and your balance is positive. How can I help you?',
    dash_chat_greeting: 'Hi! This month you have spent',
    dash_chat_spent:    'and your balance is',
    dash_chat_help:     'How can I help you?',
    dash_balance_positive: 'positive.',
    dash_balance_negative: 'negative.',
    ai_messages_left: '{n}/5 messages today',
    ph_chat:         'Ask me something about your finances...',

    lbl_debts:       'Debt Plan',
    btn_view_plan:   'View Plan',
    sub_renews:      'Renews',
    lbl_limit:       'Limit:',
    lbl_used:        'used',

    dash_view_all:   'View all',
    dash_ai_title:   '🤖 AI Assistant',
    dash_ai_online:  'Online',
    dash_chat_ph:    'Ask me something about your finances...',
    dash_vs_last:        'vs last month',
    dash_healthy:        '✓ Healthy finances',
    dash_watch:          '⚠️ Watch your spending',
    dash_critical:       '🔴 Critical: High debt',
    dash_debt_month:     '↓ this month',
    dash_messages_left:  'messages today',

    // TRANSACTIONS
    trans_title:     'Transactions',
    trans_add:       'Add Transaction',
    trans_all:       'All',
    trans_income:    'Income',
    trans_expense:   'Expense',
    trans_empty:     'No transactions yet',

    // CARDS
    cards_title:     'My Cards',
    cards_sub:       'Manage your credit and debit cards',
    btn_add_card:    '+ Add Card',
    debts_sub:       'Personalized strategy to get out of debt faster',
    btn_add_debt:    '+ Add Debt',
    tab_avalanche:   '❄️ Avalanche (Less interest)',
    tab_snowball:    '⛄ Snowball (More motivation)',
    lbl_total_debt:  'Total Debt',
    lbl_est_time:    'Estimated Time',
    lbl_min_pay:     'Total Minimum Payment',
    rec_ia_title:    '💡 AI Recommendations',

    cards_add:       'Add Card',
    card_healthy:     'Healthy',
    card_warning:     'Caution',
    card_danger:      'High use',
    card_holder:      'HOLDER',
    card_limit_label: 'LIMIT',
    card_no_name:     'No name',
    card_due:         'Due day',
    cards_personal:   '👤 Personal Cards',
    cards_business:   '🏢 Business Cards',
    card_edit_title:  '✏️ Edit Card',
    card_name_bank:   'Name / Bank',
    card_bank_label:       'Bank Name',
    card_bank_placeholder: 'e.g. Chase, Bank of America...',
    card_type_label:  'Type',
    card_limit_lbl:   'Limit ($)',
    card_balance_lbl: 'Used balance ($)',
    card_last4:       'Last 4 digits',
    card_apr:         'APR (%)',
    card_color:       'Card color',
    card_due_day:     'Due day',
    card_name_required: 'Name is required',
    card_updated:     '✅ Card updated',
    card_save_error:  'Error saving changes',
    card_deleted:     'Card deleted',
    card_delete_error:'Error deleting card',
    btn_cancel:       'Cancel',
    btn_save:         '💾 Save Changes',
    debt_add_title:    '📉 Add Debt',
    debt_name_label:      'Name (Card / Loan)',
    debt_name_placeholder:'e.g. Chase Visa...',
    debt_balance_label:   'Current Balance ($)',
    debt_min_label:       'Monthly Minimum Payment ($)',
    debt_save_btn:        '💾 Save Debt',
    debt_invalid_balance: 'Enter a valid balance',
    session_expired:      'Session expired',
    debt_added:           '✅ Debt added!',
    debt_save_error:      'Error saving debt',
    debt_deleted:         'Debt deleted',
    debt_delete_error:    'Error deleting debt',
    debts_empty:          'You have no debts registered.',
    debt_priority_high:   'HIGH Priority',
    debt_priority_med:    'MEDIUM Priority',
    debt_priority_low:    'Minimum payment for now',
    debt_used:            'used',
    debt_of:              'of',
    debt_utilized:        'utilized',
    debt_min_pay:         'Minimum payment',
    btn_delete:           'Delete',
    debts_personal:       'Personal Debts',
    debts_business:       'Business Debts',
    time_years:           'years',
    time_months:          'months',
    method_avalanche:     '❄️ Avalanche Method',
    method_snowball:      '⛄ Snowball Method',
    toast_avalanche:      '📊 Avalanche: You pay less interest overall!',
    toast_snowball:       '⛄ Snowball: More motivation to keep going!',
    cards_limit:     'Credit Limit',
    cards_used:      'Used',
    cards_available: 'Available',
    cards_empty:     'No cards added yet',

    // DEBTS
    debts_title:     'Debts',
    debts_total:     'Total Debt',
    debts_payoff:    'Estimated Payoff',
    debts_method:    'Payoff Method',
    debts_add:       'Add Debt',
    debt_method_title: '❄️ Avalanche Method',
    debt_ai_recs:    '💡 AI Recommendations',

    // SUBSCRIPTIONS
    subs_title:      'Subscriptions',
    debt_score_warn:              'Your credit score is at risk. Reducing this card below 30% could boost your score significantly.',
    debt_consol_tip:              'Your average APR is dangerously high. A personal loan at 12-15% could save you thousands — act before interest compounds further.',
    debt_at:                      'at',
    debt_free_in:                 'You could be completely debt-free in just',
    debt_save_interest:           'and keep',
    debt_extra_pay_title:         '✅ Attack your debt with an extra payment:',
    debt_high_flow_title:         '🚀 You have real power to accelerate:',
    debt_high_flow_tip:           'With {flow} free each month, putting {suggested} toward {card} could eliminate it in record time — and free up even more cash.',
    debt_invest_title:            '📈 Your cash flow opens the door to investing:',
    debt_invest_tip:              'Once your high-interest debt is gone, redirecting {amount}/month into index funds could grow to {projection} in 10 years.',
    debt_free_balance_title:      '💰 You have money working against you right now:',
    debt_free_balance_tip:        'You have {amount} sitting idle this month. Sending just {suggested} to {card} today could save you {interest} in interest over time.',
    debt_negative_balance_title:  '🚨 Your expenses are eating your future:',
    debt_negative_balance_tip:    'You are spending more than you earn. Cutting just one recurring expense could free up cash to start reversing this today.',
    debt_plan_title:              '📋 Your personalized debt-free plan:',
    debt_plan_step1:              'Step 1 — Pay minimums on all debts except {card}.',
    debt_plan_step2:              'Step 2 — Send every extra dollar to {card} ({apr}% APR).',
    debt_plan_step3:              'Step 3 — Once {card} is paid, roll that payment to the next debt.',
    debt_plan_result:             'Following this plan, you could be debt-free in {time} and save {savings} in interest.',
    subs_sub:        'Manage all your active subscriptions',
    btn_add_sub:     '+ Add',
    lbl_active_subs: 'Active Subscriptions',
    lbl_monthly_exp: 'Monthly Expense',
    lbl_annual_exp:  'Annual Expense',
    th_service:      'SERVICE',
    th_price:        'PRICE',
    th_renewal:      'RENEWAL',
    th_status:       'STATUS',
    badge_active:    'Active',
    badge_soon:      'Expiring soon',
    status_active:   'Active',
    status_due_soon: 'Due soon',

    per_month_short: '/mo',
    sub_renews:      'Renews on day',
    sub_day:         'Day',
    no_subscriptions:'No subscriptions yet',
    add_sub_short:   'Add one',
    cancel_sub:      'Cancel',

    subs_total:      'Total Monthly',
    subs_count:      'Active Subscriptions',
    subs_add:        'Add Subscription',
    subs_empty:      'No subscriptions yet',

    // SCANNER
    scan_title:      'AI Receipt Scanner',
    scan_upload:     'Drop your receipt here or click to upload',
    scan_formats:    'Supports JPG, PNG, PDF',
    scan_analyzing:  'Analyzing receipt...',
    scan_merchant:   'Merchant',
    scan_amount:     'Amount',
    scan_date:       'Date',
    scan_category:   'Category',
    scan_save:       'Save Expense',

    // REPORTS
    rep_title:       'Reports',
    rep_cat:         '📊 Expenses by Category',
    rep_monthly:     '📅 Monthly Summary 2025',
    reports_title:   '📈 Reports',
    reports_sub:     'Detailed analysis of your finances',
    btn_csv:         '⬇ CSV',
    btn_pdf:         '⬇ PDF',
    lbl_total_income:'Total Income',
    lbl_total_expense:'Total Expenses',
    lbl_transactions:'Transactions',
    rep_by_cat:      '📊 Expenses by Category',
    th_month:        'MONTH',
    th_income:       'INCOME',
    th_expense:      'EXPENSES',
    th_balance:      'BALANCE',
    month_jan:       'January',
    month_feb:       'February',
    month_mar:       'March',
    month_apr:       'April',
    month_may:       'May',
    month_jun:       'June',


    // SETTINGS
    set_title:       'Settings',
    set_profile:     '👤 Profile',
    set_subtitle:    'Customize your experience',
    lbl_name:        'Name',
    lbl_email:       'Email',
    lbl_country:     'Country',
    set_currency:    'Currency',
    set_language:    '🌐 Language',
    set_plan:        '💳 Choose your plan',
    set_notif:       '🔔 Notifications',
    set_danger:      '⚠️ Danger Zone',
    set_legal:       '⚖️ Legal',
    set_save:        'Save Changes',
    set_logout_all:  'Log Out of All Devices',
    set_delete:      'Delete Account',

    // GENERAL
    general_save:    'Save',
    general_cancel:  'Cancel',
    general_delete:  'Delete',
    general_edit:    'Edit',
    general_add:     'Add',
    general_close:   'Close',
    general_loading: 'Loading...',
    general_yes:     'Yes, delete',
    general_personal:'Personal',
    general_business:'Business',

    // TOASTS
    toast_saved:     'Saved successfully',
    toast_deleted:   'Deleted successfully',
    toast_error:     'Error. Please try again.',

    // UPGRADE MODAL
    upgrade_title:   'Upgrade your plan',
    upgrade_cta:     'See Plans',
    upgrade_cancel:  'Maybe later',

    // LIMIT BANNERS
    limit_reached:   '🚫 Limit reached',
    limit_warning:   '⚠️ used — Consider upgrading',
    limit_upgrade:   'Upgrade your plan',

    // AI CHAT
    ai_welcome:      '👋 Hi! I\'m your FinanceAI assistant. How can I help you today?',
    ai_placeholder:  'Ask me something about your finances...',
    ai_thinking:     '💭 Thinking...',
    ai_msgs_left:    'messages today',
    debt_saves_interest: 'Paying the highest interest debt first saves you more money in the long run.',
    debt_tip_text:       'Pay the card with the highest interest rate first.',
    credit_score_warn:   'Your credit score may drop. Prioritize reducing this card first.',
    badge_vence_pronto:  'Expiring soon',
    rec_based_on:        'Based on your transactions: you spend most on ',
    badge_eval:      '⚠️ Evaluate',
    subs_ia_rec:     '💡 AI Recommendation:',
    subs_ia_desc:    'Xbox Game Pass has low usage based on your patterns. Canceling it would save <strong style="color:var(--white);">$179.88/year</strong>.',
    recs_title:      '⭐ Card Recommendations',
    recs_sub:        'The best cards based on your spending habits',
    rec_ai_analysis: 'AI Analysis of your expenses',
    rec_best_general:'USA — BEST OVERALL OPTION',
    rec_best_travel: 'USA — BEST FOR TRAVEL',

    rec_desc_default:    'Available in Mexico, Colombia and Brazil. No hidden fees, full control from the app.',
    rec_best_no_fee: 'USA — BEST WITHOUT ANNUAL FEE',
    rec_latam:       'LATIN AMERICA',
    ai_section_title:'🤖 AI Financial Assistant',
    ai_section_sub:  'Powered by Google Gemini AI',
    ai_online:       '● Online',
    ai_cap_2:        '• 💳 Recommend the best card for each purchase',
    ai_cap_3:        '• 📉 Create a plan to pay off your debts',
    ai_cap_4:        '• 💡 Give you personalized advice',
    ai_cap_5:        '• 🔄 Detect subscriptions you could cancel',
    ai_cap_end:      '<br>How can I help you today?',
    quick_reduce:    '💡 Reduce expenses',
    quick_best_card: '💳 Best card',
    quick_debt_plan: '📉 Debt plan',
    quick_subs:      '🔄 Subscriptions',
    btn_send:        'Send →',

    no_trans_yet:        'No transactions yet',
    sub_scanner:         'Subscription scanner',
    badge_popular:       '🔥 MOST POPULAR',
    notif_label_4:       'Payment reminders',
    danger_zone_title:   '⚠️ Danger Zone',
    delete_account_btn:  'Delete Account',
    legal_title:         '⚖️ Legal',
    legal_terms_title:   '📋 Terms of Service',
    legal_terms_desc:    'FinanceAI Pro terms and conditions',
    legal_privacy_title: '🔒 Privacy Policy',
    legal_privacy_desc:  'How we protect your data',
    copyright_text:      '© 2025 Climberforsuccess LLC · All rights reserved',
    admin_page_title:    '🔐 Admin Panel',
    admin_page_subtitle: 'Climberforsuccess LLC — Control Panel',
    admin_label_total:   '👥 Total Users',
    admin_label_vip:     '👑 VIP Users',
    admin_label_codes:      '🎁 Codes Used',
    admin_label_ai_calls:   '🤖 AI Calls Today',
    admin_vip_mgmt_title:   '🎁 VIP Code Management',
    admin_gen_code_label:   'Generate new code:',
    admin_opt_personal:     '⚡ VIP Personal',
    admin_opt_familia:      '👨‍👩‍👧 VIP Family',
    admin_opt_1m:           '1 month',
    admin_opt_3m:           '3 months',
    admin_opt_6m:           '6 months',
    admin_opt_12m:          '1 year',
    admin_gen_code_btn:     '✨ Generate Code',
    admin_code_generated:   'Generated code:',
    admin_code_generated_label: 'Generated code:',
    admin_copy_btn:         '📋 Copy',
    admin_session_codes:    'Codes generated this session:',
    admin_no_codes_msg:     'No codes generated yet',
    admin_used_codes_title: '📊 VIP Codes Used',
    admin_loading_msg:      'Loading...',
    admin_activate_vip:     '🌟 Activate VIP Plan',
    vip_status_sub_text:    '5 AI messages per day',
    admin_vip_enter_label:  'Have a VIP code? Enter it here:',
    activate_vip_btn:    'Activate',
    or_buy_plan:         'or buy a plan',
    vip_personal_name:   '⚡ VIP Personal',
    vip_personal_badge:  'Popular',
    vip_personal_f1:     '✅ Unlimited AI messages',
    vip_personal_f2:     '✅ Full GPT-4o access',
    vip_personal_f4:     '✅ Advanced reports',
    get_vip_personal:    '🚀 Get VIP Personal',
    vip_familia_name:    '👨‍👩‍👧 VIP Family',
    vip_familia_f1:      '✅ Everything in Personal',
    vip_familia_f2:      '✅ Up to 5 family accounts',
    vip_familia_f3:      '✅ Shared family dashboard',
    vip_familia_f4:      '✅ Priority support',
    get_vip_familia:     '👨‍👩‍👧 Get VIP Family',
    legal_back_btn:      '← Back',
    modal_upgrade_title: 'Upgrade Your Plan',
    btn_monthly:         'Monthly',
    btn_annual:          'Annual',
    btn_monthly_label:   'Monthly',
    btn_annual_label:    'Annual',
    btn_annual_save:     'Save 17%',
    tab_stripe:          '💳 Card (Stripe)',
    tab_paypal:          '🅿️ PayPal',
    modal_secure:        '🔒 Secure • Cancel anytime • No hidden fees',
    feat_unlimited_tx:  'Unlimited transactions',
    feat_basic_reports: 'Basic reports',
    feat_all_pro:       'Everything in Pro',
    feat_5_users:       'Up to 5 users',
    feat_admin_panel:   'Admin panel',
    feat_biz_reports:   'Business reports',
    feat_support_247:   'Priority support 24/7',
    lbl_login_pass:     'Password',
    lbl_reg_name:       'Full Name',
    lbl_reg_plan:       'Plan',
    nav_admin_label:    'Admin Panel',
    scan_tip_1:         'Make sure the receipt is fully visible',
    scan_tip_2:         'Good lighting for better recognition',
    scan_tip_3:         'Keep the phone steady when photographing',
    scan_tip_4:         'Works with receipts in English and Spanish',
    tx_title:        '💰 Transactions',
    tx_sub:          'All your income and expenses',
    btn_new_tx:      '+ New Transaction',
    tab_all:         'All',
    tab_income:      'Income',
    tab_expense:     'Expenses',
    tab_personal:    'Personal',
    tab_business:    'Business',
    th_desc:         'DESCRIPTION',
    th_cat:          'CATEGORY',
    th_type:         'TYPE',
    th_date:         'DATE',
    th_amount:       'AMOUNT',
    th_actions:      'ACTIONS',
    tx_confirm_delete:       'Are you sure you want to delete this transaction?',
    notif_tx_deleted:        'Transaction deleted successfully',
    tx_alert_error:          'Error saving: ',

    card_type_credit:   'Credit',
    card_type_debit:    'Debit',
    card_type_prepaid:  'Prepaid',
    card_used:          'used',
    btn_edit:           'Edit',
    sub_day:            'Day',
    sub_billing_day:    'Billing Day (1-31)',
    sub_category:       'Category',
    cat_music:          'Music',
    cat_design:         'Design',
    sub_save:           '💾 Save Subscription',
    scan_upload_hint:   'Click here or drag an image · JPG, PNG, HEIC',
    col_date:           'Date',
    col_desc:           'Description',
    col_cat:            'Category',
    col_amount:         'Amount',
    reports_empty_1:    '📊 Your monthly summary will appear here —',
    reports_empty_2:    'Add your first transaction and start seeing results →',
    vip_invalid_code:   'Enter a valid code.',
    vip_code_used:      'This code has already been used.',
    vip_code_wrong:     'Invalid code. Please verify and try again.',
    vip_code_ok:        '✅ Code activated! VIP Plan',
    vip_months:         'for',
    cta_control_now:    '⚡ Yes, I want to control my money now',
    legal_recurring:    'Charges are recurring (monthly or annual depending on the plan chosen)',
    legal_no_refunds:   'No refunds are issued for partial periods',
    legal_price_change: 'Prices may change with 30 days prior notice',
    up_scanner_title:      '📸 Do you save paper receipts?',
    scanner_title:   '📸 AI Receipt Scanner',
    scanner_sub:     'Photograph your receipt and AI detects everything automatically',
    upload_title:    'Upload Receipt Photo',
    upload_sub:      'Click here or drag an image · JPG, PNG, HEIC',
    ia_detected:     'AI detected:',
    lbl_merchant:    '🏪 Merchant',
    lbl_amount:      '💵 Total Amount',
    lbl_category:    '📁 Category',
    lbl_date:        '📅 Date',
    lbl_card_rec:    '💳 Recommended Card',
    lbl_type:        '🏷️ Type',
    opt_personal:    'Personal',
    opt_business:    'Business',
    btn_save_tx:     '✓ Save Transaction',
    btn_discard:     '× Discard',
    tips_title:      '💡 Tips for better results',

    up_scanner_desc:       'The 73% of expenses are forgotten in less than 48 hours. With the AI scanner you capture every expense in seconds and never lose money without knowing it.',
    up_reports_title:      '📊 Your money has hidden patterns',
    up_reports_desc:       'Advanced reports reveal exactly where you overspend, when and why. Pro users save on average $300/month just with this feature.',
    up_gpt4_title:         '🤖 Your personal financial advisor, 24/7',
    up_gpt4_desc:          'GPT-4o analyzes your finances in depth, detects risks, suggests savings and answers any question about your money — like having a CFO in your pocket.',
    up_export_title:       '📤 Take your finances anywhere',
    up_export_desc:        'Export to PDF or Excel to share with your accountant, bank or simply for your personal records. Professionalize your money management.',
    up_cards_title:        '💳 You have reached your card limit!',
    up_cards_desc:         'Millions went into debt for lack of control. You can be different — add all your cards and know exactly how much you owe, when and to whom.',
    up_multiuser_title:    '👥 Multi-User',
    up_multiuser_desc:     'Share access with your family or work team.',
    up_api_title:          '🔌 API Access',
    up_api_desc:           'Integrate FinanceAI Pro with your own applications.',
    up_transactions_title: '📝 Almost out of space!',
    up_transactions_desc:  'Every unrecorded transaction is money you lose without knowing it. Do not stop now — unlock unlimited tracking and maintain total control of your money.',
    tx_cat_placeholder: 'e.g. Food, Transport...',
    tx_new_title:       '+ New Transaction',
    summary_income:     'Total Income',
    summary_expenses:   'Total Expenses',
    plan_pro_name:       '💎 Pro',
    plan_pro_real_price: 'Real value $39.99/mo',
    pro_f1:              '✅ <strong>Unlimited AI 24/7</strong>',
    pro_f2:              '✅ <strong>GPT-4o</strong> — the most advanced AI',
    pro_f3:              '✅ Unlimited transactions · Up to 10 cards',
    pro_f4:              '✅ Smart receipt scanner',
    pro_f5:              '✅ Advanced reports with insights',
    pro_f6:              '✅ AI financial goals',
    pro_f7:              '✅ <strong>Save $340/mo on average</strong>',
    cta_pro_label:       '⚡ I want to save $340/mo — ',
    pro_cancel_note:     '✅ Cancel anytime · 100% secure payment',
    plan_business_name:  '🏢 Business',
    biz_f1:              '✅ Everything in Pro',
    biz_f2:              '✅ Up to 5 users',
    biz_f3:              '✅ Team management',
    biz_f4:              '✅ Business reports',
    biz_f5:              '✅ Priority support 24/7',
    biz_f6:              '✅ API Access for integrations',
    biz_f7:              '✅ Unlimited cards and users',
    biz_f8:              '✅ <strong>Guaranteed ROI or money back</strong>',
    cta_business_label:  '🏢 Power your business — ',
    testimonial_quote:   '"I recovered $180 in the first month detecting forgotten subscriptions and unnecessary expenses"',
    testimonial_author:  '— María G., Pro user since 2024',
    vip_code_label:      'Do you have a VIP code?',
    notif_label_1:       'Subscription alerts',
    notif_label_2:       'Unusual expenses',
    notif_label_3:       'Weekly summary',
    current_plan_label:   '✨ Current plan: FREE',
    pricing_tagline:      'Invest less than a coffee a day and recover hundreds a month',
    plan_free_name:       '🆓 Free',
    plan_free_period:     '/mo',
    modal_free_f5:        '❌ No advanced reports',
    modal_free_f6:        '❌ No GPT-4o',
    btn_free_label:       'Free forever',
    vip_status_label:     'Current plan:',
    vip_plan_name:        'Free',
    billing_monthly:      'Monthly',
    billing_annual:       'Annual',
    annual_savings_text:  '🎉 Pay annually and save up to <strong>$120/yr</strong> — 2 months FREE',
    plan_personal_name:   '⭐ Personal',
    modal_personal_f1:    '✅ Unlimited transactions',
    modal_personal_f2:    '✅ Basic reports',
    modal_personal_f3:    '❌ No GPT-4o',
    cta_personal_label:   '🚀 Start now — Only ',
    toast_payments_soon:    '💳 Payments available very soon. Use a VIP code for now!',
    btn_apply:               '✅ Apply',
    debt_consol_title:       '💡 Consolidation:',
    debt_balance_title:      '💰 Positive balance:',
    vip_code_placeholder:    'Enter your code',
    admin_vip_placeholder:   'e.g. VIP-XXXX-XXXX',
    notif_coming_soon:       '⚠️ Feature coming soon',
    ph_password_min:        'Minimum 8 characters',
    ph_select_country:      'Select your country',
    plan_free_option:       'Free — $0/mo',
    plan_personal_option:   'Personal — $9.99/mo',
    plan_pro_option:        'Pro — $19.99/mo',
    plan_business_option:   'Business — $49.99/mo',
    ph_email:               'your@email.com',
    price_suffix_monthly:    '/mo',
    price_suffix_annual:     '/mo (annual)',
    ph_name:                'Your name',
    sub_scanner:       'Take a photo of your receipt and AI detects everything automatically',
    sub_cards:         'Manage your credit and debit cards',
    title_rec_ia:      '💡 AI Recommendations',
    sub_subs:          'Manage all your active subscriptions',
    debt_rec_ia_label: '💡 AI Recommendation:',
    title_card_recs:   '⭐ Card Recommendations',
    sub_card_recs:     'The best cards according to your spending habits',
    ai_greeting:       '🤖 Hi! I\'m your personal financial assistant powered by Google Gemini AI.',
    ai_can_help:       'I can help you with:',
    ai_cap_1:          '• 📊 Analyze your expenses and income',
    pf3:             '50 AI messages per day',
    pf4:             'Up to 3 cards',
    pf5:             'Receipt Scanner',
    modal_free_f1:   '✅ 5 AI messages per day',
    modal_free_f2:   '✅ Up to 30 transactions',
    modal_free_f3:   '✅ 1 card',
    modal_free_f4:   '❌ No receipt scanner',
    modal_pro_f1:    '✅ 50 AI messages per day',
    modal_pro_f2:    '✅ Up to 3 cards',
    modal_pro_f3:    '✅ Receipt Scanner',
    upgrade_li_scanner: '✅ Receipt Scanner',
    pf1:             'Up to 50 transactions/month',
    pf2:             '1 credit card',
    ai_msgs_today:   '5/5 messages today',

    // APP.HTML data-key mappings
    dash_dashboard:      'Dashboard',
    dash_receipts:       'Receipt Scanner',
    dash_transactions:   'Transactions',
    dash_cards:          'My Cards',
    dash_debt:           'Debt Plan',
    dash_subscriptions:  'Subscriptions',
    dash_ai:             'AI Assistant',
    dash_settings:       'Settings',
    dash_welcome:        'Welcome back',
    dash_scan:           'Scan Receipt',
    dash_income:         'Monthly Income',
    dash_expenses:       'Monthly Expenses',
    dash_balance:        'Total Balance',
    dash_savings:        'Savings Rate',
    dash_recent:         'Recent Transactions',
    dash_quick:          'Quick Actions',
    dash_add:            'Add Transaction',
    dash_plan:           'View Debt Plan',
    dash_recommend:      'Card Recommendations',
    scan_result:         'Detected Expense',
    scan_type:           'Type',
    scan_rescan:         'Scan Another',
    cards_recommend:     'Best Card For...',
    debt_title:          'Debt Payoff Plan',
    debt_add:            'Add Debt',
    debt_monthly:        'Monthly Payment',
    debt_payoff:         'Est. Payoff',
    debt_interest:       'Interest Saved',
    debt_method:         'Payoff Method',
    debt_avalanche:      'Avalanche (Highest Interest First)',
    debt_snowball:       'Snowball (Smallest Balance First)',
    debt_name:           'Debt Name',
    debt_balance:        'Balance',
    debt_min:            'Min. Payment',
    debt_rate:           'Interest Rate',
    debt_save:           'Save Debt',
    subs_next:           'Next Charge',
    ai_title:            'AI Assistant',
    ai_suggestions:      'Try asking:',
    settings_title:      'Settings',
    settings_profile:    'Profile',
    settings_currency:   'Currency',
    settings_language:   'Language',
    settings_plan:       'Current Plan',
    settings_upgrade:    'Upgrade Plan',
    settings_save:       'Save Changes',
    settings_notifications: 'Notifications',

    // DYNAMIC MESSAGES
    upgrade_available:      'Available from plan',
    upgrade_warning:        '🚨 Only {n} transactions left — upgrade now!',
    ai_limit_reached:       '🔒 You have reached your 5 messages/day limit. Upgrade to VIP for unlimited messages! 🌟',
    ai_limit_daily:         '🔒 Daily limit reached. Upgrade to VIP! 🌟',
    ai_msgs_day:            '5 AI messages per day',
    ai_msgs_warning:        '⚠️ {n} AI messages left today — consider upgrading',
    trans_empty_cat:        'No transactions in this category.',
    trans_export_empty:     'No transactions to export yet — add some!',
    export_filename:        'financeai_transactions',
    credit_limit:           'Credit limit',

    // TOASTS & DYNAMIC UI
    subs_invalid_amount:    'Enter a valid amount',
    subs_save_error:        'Error saving subscription',
    subs_deleted:           'Subscription deleted',
    subs_delete_error:      'Error deleting subscription',
    plan_vip_sub:           'Unlimited messages · Expires in {n} days',
    plan_free:              'Free',
    plan_free_forever:      'Free forever',
    plan_current:           'Your current plan',
    plan_current_free:      'Your current plan — Free',
    plan_expires:           'Expires in {n} days',
    plan_actual:            'Current plan:',
    current_plan_badge:     '✨ Your current plan:',
    receipt_scanned:        'Scanned receipt',
    btn_save_card:          'Save',
    scan_requires_plan:     'Scanner requires Personal plan or higher',
    pay_with_card:          '💳 Pay with Card (Stripe)',
    secure_payment:         '🔒 Secure payment powered by Stripe',
    payment_failed:         'Payment failed. Please try again.',
    loading_paypal:         'Loading PayPal...',
    payment_cancelled:      'Payment cancelled.',
    try_again:              'Try again',
    could_not_load_paypal:  'Could not load PayPal. Please use card payment.',
    could_not_load_sdk:     'Could not load PayPal SDK.',
    payment_success:        'Payment Successful!',
    welcome_pro:            'Welcome to FinanceAI Pro',
    redirecting_dashboard:  'Redirecting to dashboard...',
    processing:             'Processing...',
    upgrade_required:       'Upgrade Required',
    requires_plan:          'requires the',
    plan_or_higher:         'plan or higher.',
    maybe_later:            'Maybe Later',
    upgrade_now:            'Upgrade Now',
    scan_unknown:           'Unknown',
    scan_other:             'Other',
    scan_error:             'Error analyzing receipt. Try another image.',
    scan_no_data:           'No receipt data to save',
    scan_save_error:        'Error saving transaction',
    scan_read_error:        'Could not read receipt — try with better lighting 📸',
    scan_first:             'Scan a receipt first 📸',
    scan_save_error2:       'Error saving — try again in a moment',
    pdf_ready:              '✅ PDF ready — use "Save as PDF" in the print dialog 🎉',
    card_name_required:     'Enter the cardholder name',
    card_save_error:        'Error saving card',
    // AUTH
    sign_in:                'Sign In',
    error_password_length:  'Password must be at least 6 characters',
    please_enter_credentials: 'Please enter email and password',
    fill_all_fields:          'Please fill in all fields',
    account_created:          'Account created! Check your email to verify your account.',
    enter_email_first:        'Enter your email first',
    password_reset_sent:      'Password reset email sent! Check your inbox.',
    ai_proxy_ready:   'OpenAI proxy ready via Supabase Edge Function',
    messages_vip:     '∞ messages (VIP)',
    messages_today:   ' messages today',
    plan_label:              'Plan:',
    amount_label:            'Amount:',
    could_not_create:        'Could not create checkout session',
    paypal_failed:           'PayPal payment failed. Please try again.',
    plan_personal_price:     'Personal ($9.99/mo)',
    plan_pro_price:          'Pro ($19.99/mo)',
    plan_business_price:     'Business ($49.99/mo)',
    subs_added:              '✅ Subscription added!',
    subs_detected:           '💡 Subscription detected: ',
    code_generated:          'generated',
    code_copied_clipboard:   '📋 Code copied to clipboard',
    code_copied:             '📋 Copied',
    login_required:          '⚠️ Please log in to continue',
    processing_payment:      '🔒 Processing',
    redirecting_stripe:      '🚀 Redirecting to secure Stripe payment!',
    stripe_session_error:    '❌ Error creating payment session — please try again',
    connection_error:        '❌ Connection error — check your internet',
    transaction_saved:       '✅ Transaction saved successfully',
    scanner_unlock:          '✨ Unlock AI Scanner — save hours every week',
    receipt_detected:        '🎯 Receipt detected! Review the data and save in 1 click',
    saved_history:           '✅ Saved! Your financial history updates automatically 🚀',
    export_requires_pro:     '📤 Export requires Pro plan — take your finances to the next level!',
    code_label:              'Code',
    months_label:            'month(s)',
    no_codes_generated:      'No codes generated yet',
    no_codes_activated:      'No codes activated yet',
    scanning_receipt:        'Analyzing receipt with AI...',
    ai_reading_receipt:      'Your AI is reading the receipt...',
    ai_reading_seconds:      'This only takes a few seconds',
    receipt_analyzed:        'Receipt analyzed successfully',
    receipt_analyzed_ok:     'Receipt analyzed correctly',
    scan_again:              'Click to scan another receipt',
    upload_receipt_title:    'Upload Receipt Photo',
    upgrade_social_proof:    '⚡ Thousands of users already control their finances with this',
    upgrade_one_step:        'You are 1 step away from total control of your money 💡',
    upgrade_unlock_btn:      '🔓 Unlock Now — See Plans',
    upgrade_dismiss:         'No, I prefer to keep losing money without knowing it',
    no_transactions:         'You have no registered transactions.',
    no_description:          'No description',
    no_subscriptions:        'You have no subscriptions.',
    add_sub_short:           '+ Add',
    per_month_short:         '/month',
    add_sub_title:           '🔄 Add Subscription',
    sub_name_label:          'Service Name',
    sub_amount_label:        'Monthly Amount ($)',
    ai_analyzing:            '⏳ Analyzing...',
    ai_connect_error:        '❌ Error connecting to AI. Please try again.',
    upgrade_limited_offer:   '⚡ Limited offer — Today only',
    upgrade_losing_money:    "You're losing money<br>without knowing it",
    upgrade_ai_limit_desc:   'You reached your free AI limit. Pro users detect hidden expenses and save an average of <strong style="color:#f59e0b;">$340/month</strong>. How much are you losing?',
    upgrade_unlock_all:      '🔓 Unlock everything now:',
    upgrade_feat_ai:         '<strong>Unlimited AI 24/7</strong> — your personal financial advisor always available',
    upgrade_feat_gpt4:       "<strong>GPT-4o</strong> — detects spending patterns you don't see",

    upgrade_feat_scanner:    '<strong>Smart Scanner</strong> — log receipts in 2 seconds',
    upgrade_feat_reports:    '<strong>Reports that save you money</strong> — see exactly where your money goes',
    upgrade_feat_goals:      '<strong>AI Goals</strong> — reach financial freedom faster',
    upgrade_real_value:      'Real value: $29.99/month',
    upgrade_today_get:       'Today you get it for',
    upgrade_cancel_anytime:  '✅ Cancel anytime · No contracts',
    upgrade_annual_deal:     '💰 Best deal: Annual plan — Save 40%',
    upgrade_social_proof2:   '⭐⭐⭐⭐⭐ <strong style="color:#fff;">+1,200 users</strong> already in control of their money',
    upgrade_testimonial:     '"I recovered $180 in the first month detecting forgotten subscriptions" — María G.',
    upgrade_no_thanks:       "I'm not interested in saving money right now",
    ctx_total_income:        '- Total income',
    ctx_total_expense:       '- Total expenses',
    ctx_net_balance:         '- Net balance',
    ctx_total_debt:          '- Total debt',
    ctx_cards:               '- Cards',
    ctx_subscriptions:       '- Subscriptions',
    ctx_plan:                '- Plan',
    cat_productivity:        'Productivity',
    cat_storage:             'Storage',
    cat_shopping:            'Shopping',
    cat_gaming:              'Gaming',
    cat_fitness:             'Fitness',
    cat_other:               'Other',
    // AUTH TABS & FORM
    tab_login:              'Sign In',
    tab_register:           'Sign Up',
    lbl_password:           'Password',
    forgot_password:        'Forgot your password?',
    recover_password:       'Recover',
    // REGISTER FORM
    lbl_plan:               'Plan',
    create_account:         'Create Account',
    terms_accept:           'I accept the',
    terms_service:          'Terms of Service',
    privacy_policy:         'Privacy Policy',
    terms_and:              'and the',
    tx_label_desc:           'Description',
    tx_placeholder_desc:     'e.g. Salary, Netflix, Groceries...',
    tx_label_amount:         'Amount',
    tx_label_type:           'Type',
    tx_opt_income:           'Income',
    tx_opt_expense:          'Expense',
    tx_label_owner:          'Is this personal or business?',
    tx_opt_personal:         'Personal',
    tx_opt_business:         'Business',
    tx_label_category:       'Category',
    tx_label_date:           'Date',
    nav_terms:               'Terms of Service',
    nav_privacy:             'Privacy Policy',
    nav_cookies:             '🍪 Cookies',
    btn_close:               '✖ Close',
    debt_method_avalanche_desc: '📊 Pay highest interest rate first — saves the most money overall',
    debt_method_snowball_desc:  '⛄ Pay smallest balance first — builds momentum and motivation',
  },

  es: {
    badge_popular:       '🔥 MÁS POPULAR',
    notif_label_4:       'Recordatorio de pagos',
    danger_zone_title:   '⚠️ Zona de Peligro',
    delete_account_btn:  'Eliminar Cuenta',
    legal_title:         '⚖️ Legal',
    legal_terms_title:   '📋 Términos de Servicio',
    legal_terms_desc:    'Condiciones de uso de FinanceAI Pro',
    legal_privacy_title: '🔒 Política de Privacidad',
    legal_privacy_desc:  'Cómo protegemos tus datos',
    copyright_text:      '© 2025 Climberforsuccess LLC · Todos los derechos reservados',
    admin_page_title:    '🔐 Admin Panel',
    admin_page_subtitle: 'Climberforsuccess LLC — Panel de Control',
    admin_label_total:   '👥 Usuarios Totales',
    admin_label_vip:     '👑 Usuarios VIP',
    admin_label_codes:      '🎁 Códigos Usados',
    admin_label_ai_calls:   '🤖 Llamadas IA Hoy',
    admin_vip_mgmt_title:   '🎁 Gestión de Códigos VIP',
    admin_gen_code_label:   'Generar nuevo código:',
    admin_opt_personal:     '⚡ VIP Personal',
    admin_opt_familia:      '👨‍👩‍👧 VIP Familia',
    admin_opt_1m:           '1 mes',
    admin_opt_3m:           '3 meses',
    admin_opt_6m:           '6 meses',
    admin_opt_12m:          '1 año',
    admin_gen_code_btn:     '✨ Generar Código',
    admin_code_generated:   'Código generado:',
    admin_code_generated_label: 'Código generado:',
    admin_copy_btn:         '📋 Copiar',
    admin_session_codes:    'Códigos generados esta sesión:',
    admin_no_codes_msg:     'No hay códigos generados aún',
    admin_used_codes_title: '📊 Códigos VIP Usados',
    admin_loading_msg:      'Cargando...',
    admin_activate_vip:     '🌟 Activar Plan VIP',
    vip_status_sub_text:    '5 mensajes IA por día',
    admin_vip_enter_label:  '¿Tienes un código VIP? Ingrésalo aquí:',
    activate_vip_btn:    'Activar',
    or_buy_plan:         'o compra un plan',
    vip_personal_name:   '⚡ VIP Personal',
    vip_personal_badge:  'Popular',
    vip_personal_f1:     '✅ Mensajes IA ilimitados',
    vip_personal_f2:     '✅ GPT-4o acceso completo',
    vip_personal_f4:     '✅ Reportes avanzados',
    get_vip_personal:    '🚀 Obtener VIP Personal',
    vip_familia_name:    '👨‍👩‍👧 VIP Familia',
    vip_familia_f1:      '✅ Todo lo de Personal',
    vip_familia_f2:      '✅ Hasta 5 cuentas familiares',
    vip_familia_f3:      '✅ Dashboard familiar compartido',
    vip_familia_f4:      '✅ Soporte prioritario',
    get_vip_familia:     '👨‍👩‍👧 Obtener VIP Familia',
    legal_back_btn:      '← Volver',
    modal_upgrade_title: 'Mejora Tu Plan',
    btn_monthly:         'Mensual',
    btn_annual:          'Anual',
    btn_monthly_label:   'Mensual',
    btn_annual_label:    'Anual',
    btn_annual_save:     'Ahorra 17%',
    tab_stripe:          '💳 Tarjeta (Stripe)',
    tab_paypal:          '🅿️ PayPal',
    modal_secure:        '🔒 Seguro • Cancela cuando quieras • Sin cargos ocultos',
    feat_unlimited_tx:  'Transacciones ilimitadas',
    feat_basic_reports: 'Reportes básicos',
    feat_all_pro:       'Todo lo de Pro',
    feat_5_users:       'Hasta 5 usuarios',
    feat_admin_panel:   'Panel de administración',
    feat_biz_reports:   'Reportes empresariales',
    feat_support_247:   'Soporte prioritario 24/7',
    lbl_login_pass:     'Contraseña',
    lbl_reg_name:       'Nombre Completo',
    lbl_reg_plan:       'Plan',
    nav_admin_label:    'Admin Panel',
    scan_tip_1:         'Asegúrate de que el recibo esté completamente visible',
    scan_tip_2:         'Buena iluminación para mejor reconocimiento',
    scan_tip_3:         'Mantén el teléfono estable al fotografiar',
    scan_tip_4:         'Funciona con recibos en inglés y español',
    tx_title:        '💰 Transacciones',
    tx_sub:          'Todos tus ingresos y gastos',
    btn_new_tx:      '+ Nueva Transacción',
    tab_all:         'Todas',
    tab_income:      'Ingresos',
    tab_expense:     'Gastos',
    tab_personal:    'Personal',
    tab_business:    'Empresa',
    th_desc:         'DESCRIPCIÓN',
    th_cat:          'CATEGORÍA',
    th_type:         'TIPO',
    th_date:         'FECHA',
    th_amount:       'MONTO',
    th_actions:      'ACCIONES',

    card_type_credit:   'Crédito',
    card_type_debit:    'Débito',
    card_type_prepaid:  'Prepago',
    card_used:          'usado',
    btn_edit:           'Editar',
    sub_day:            'Día',
    sub_billing_day:    'Día de Cobro (1-31)',
    sub_category:       'Categoría',
    cat_music:          'Música',
    cat_design:         'Diseño',
    sub_save:           '💾 Guardar Suscripción',
    scan_upload_hint:   'Click aquí o arrastra una imagen · JPG, PNG, HEIC',
    col_date:           'Fecha',
    col_desc:           'Descripción',
    col_cat:            'Categoría',
    col_amount:         'Monto',
    reports_empty_1:    '📊 Tu resumen mensual aparecerá aquí —',
    reports_empty_2:    'Agrega tu primera transacción y empieza a ver resultados →',
    vip_invalid_code:   'Ingresa un código válido.',
    vip_code_used:      'Este código ya fue usado.',
    vip_code_wrong:     'Código inválido. Verifica e intenta de nuevo.',
    vip_code_ok:        '✅ ¡Código activado! Plan VIP',
    vip_months:         'por',
    cta_control_now:    '⚡ Sí, quiero controlar mi dinero ahora',
    legal_recurring:    'Los cargos son recurrentes (mensual o anual según el plan elegido)',
    legal_no_refunds:   'No se emiten reembolsos por períodos parciales',
    legal_price_change: 'Los precios pueden cambiar con previo aviso de 30 días',
    up_scanner_title:      '📸 ¿Guardas recibos en papel?',
    scanner_title:   '📸 Escáner de Recibos IA',
    scanner_sub:     'Fotografía tu recibo y la IA detecta todo automáticamente',
    upload_title:    'Subir Foto del Recibo',
    upload_sub:      'Click aquí o arrastra una imagen · JPG, PNG, HEIC',
    ia_detected:     'IA detectó:',
    lbl_merchant:    '🏪 Comercio',
    lbl_amount:      '💵 Monto Total',
    lbl_category:    '📁 Categoría',
    lbl_date:        '📅 Fecha',
    lbl_card_rec:    '💳 Tarjeta Recomendada',
    lbl_type:        '🏷️ Tipo',
    opt_personal:    'Personal',
    opt_business:    'Empresa',
    btn_save_tx:     '✓ Guardar Transacción',
    btn_discard:     '× Descartar',
    tips_title:      '💡 Tips para mejores resultados',

    up_scanner_desc:       'El 73% de los gastos se olvidan en menos de 48 horas. Con el scanner de IA capturas cada gasto en segundos y nunca más pierdes dinero sin saberlo.',
    up_reports_title:      '📊 Tu dinero tiene patrones ocultos',
    up_reports_desc:       'Los reportes avanzados revelan exactamente en qué gastas de más, cuándo y por qué. Usuarios Pro ahorran en promedio $300/mes solo con esta función.',
    up_gpt4_title:         '🤖 Tu asesor financiero personal, 24/7',
    up_gpt4_desc:          'GPT-4o analiza tus finanzas en profundidad, detecta riesgos, sugiere ahorros y responde cualquier pregunta sobre tu dinero — como tener un CFO en tu bolsillo.',
    up_export_title:       '📤 Lleva tus finanzas a cualquier lugar',
    up_export_desc:        'Exporta en PDF o Excel para compartir con tu contador, banco o simplemente para tu archivo personal. Profesionaliza el control de tu dinero.',
    up_cards_title:        '💳 ¡Alcanzaste tu límite de tarjetas!',
    up_cards_desc:         'Millones se endeudaron por no tener control. Tú puedes ser diferente — agrega todas tus tarjetas y sabe exactamente cuánto debes, cuándo y a quién.',
    up_multiuser_title:    '👥 Multi-Usuario',
    up_multiuser_desc:     'Comparte el acceso con tu familia o equipo de trabajo.',
    up_api_title:          '🔌 API Access',
    up_api_desc:           'Integra FinanceAI Pro con tus propias aplicaciones.',
    up_transactions_title: '📝 ¡Casi sin espacio!',
    up_transactions_desc:  'Cada transacción no registrada es dinero que pierdes sin saberlo. No pares ahora — desbloquea el registro ilimitado y mantén el control total de tu dinero.',
    tx_cat_placeholder: 'Ej: Alimentación, Transporte...',
    tx_new_title:       '+ Nueva Transacción',
    summary_income:     'Total Ingresos',
    summary_expenses:   'Total Gastos',
    plan_pro_name:       '💎 Pro',
    plan_pro_real_price: 'Valor real $39.99/mes',
    pro_f1:              '✅ <strong>IA ilimitada 24/7</strong>',
    pro_f2:              '✅ <strong>GPT-4o</strong> — la IA más avanzada',
    pro_f3:              '✅ Transacciones ilimitadas · Hasta 10 tarjetas',
    pro_f4:              '✅ Scanner inteligente de recibos',
    pro_f5:              '✅ Reportes avanzados con insights',
    pro_f6:              '✅ Metas financieras con IA',
    pro_f7:              '✅ <strong>Ahorra $340/mes en promedio</strong>',
    cta_pro_label:       '⚡ Quiero ahorrar $340/mes — ',
    pro_cancel_note:     '✅ Cancela cuando quieras · Pago 100% seguro',
    plan_business_name:  '🏢 Business',
    biz_f1:              '✅ Todo lo de Pro',
    biz_f2:              '✅ Hasta 5 usuarios',
    biz_f3:              '✅ Gestión de equipo',
    biz_f4:              '✅ Reportes empresariales',
    biz_f5:              '✅ Soporte prioritario 24/7',
    biz_f6:              '✅ API Access para integraciones',
    biz_f7:              '✅ Tarjetas y usuarios ilimitados',
    biz_f8:              '✅ <strong>ROI garantizado o devolvemos tu dinero</strong>',
    cta_business_label:  '🏢 Potencia tu negocio — ',
    testimonial_quote:   '"Recuperé $180 el primer mes detectando suscripciones olvidadas y gastos innecesarios"',
    testimonial_author:  '— María G., usuaria Pro desde 2024',
    vip_code_label:      '¿Tienes un código VIP?',
    notif_label_1:       'Alertas de suscripciones',
    notif_label_2:       'Gastos inusuales',
    notif_label_3:       'Resumen semanal',
    current_plan_label:   '✨ Tu plan actual: FREE',
    pricing_tagline:      'Invierte menos que un café al día y recupera cientos al mes',
    plan_free_name:       '🆓 Free',
    plan_free_period:     '/mes',
    modal_free_f5:        '❌ Sin reportes avanzados',
    modal_free_f6:        '❌ Sin GPT-4o',
    btn_free_label:       'Gratis para siempre',
    vip_status_label:     'Plan actual:',
    vip_plan_name:        'Gratuito',
    billing_monthly:      'Mensual',
    billing_annual:       'Anual',
    annual_savings_text:  '🎉 Pagas anual y ahorras hasta <strong>$120/año</strong> — 2 meses GRATIS',
    plan_personal_name:   '⭐ Personal',
    modal_personal_f1:    '✅ Transacciones ilimitadas',
    modal_personal_f2:    '✅ Reportes básicos',
    modal_personal_f3:    '❌ Sin GPT-4o',
    cta_personal_label:   '🚀 Empezar ahora — Solo ',
    toast_payments_soon:    '💳 Pagos disponibles muy pronto. ¡Usa un código VIP por ahora!',
    btn_apply:               '✅ Aplicar',
    debt_consol_title:       '💡 Consolidación:',
    debt_balance_title:      '💰 Balance positivo:',
    vip_code_placeholder:    'Ingresa tu código',
    admin_vip_placeholder:   'Ej: VIP-XXXX-XXXX',
    notif_coming_soon:       '⚠️ Función disponible próximamente',
    // NAVBAR
    modal_title:     'Aviso',
    landing_original_personal: 'Precio normal $9.99/mes',
    landing_original_pro:      'Valor real $39.99/mes',
    landing_original_business: 'Precio normal $49.99/mes',
    pf3_dashboard:             'Dashboard básico',
    nav_features:    'Funciones',
    nav_pricing:     'Precios',
    nav_login:       'Entrar',
    nav_start:       'Empezar Gratis',

    // HERO
    hero_badge:      '✨ POWERED BY AI — GRATIS PARA EMPEZAR',
    hero_title:      'Toma el Control de tus <span style="color:#00EEFF">Finanzas</span> con Inteligencia Artificial',
    hero_desc:       'Escanea recibos, gestiona deudas, descubre las mejores tarjetas y recibe recomendaciones personalizadas con IA. Todo en un solo lugar.',
    hero_cta:        '🚀 Empezar Gratis Ahora',
    hero_demo:       'Ver Demo',
    landing_btn_monthly: 'Mensual',
    landing_btn_annual:  'Anual',
    landing_savings_banner: '🎉 Pago anual = 2 meses GRATIS — Ahorras hasta <strong>$120/año</strong>',
    stat1:           'Usuarios Activos',
    stat2:           'En Deudas Gestionadas',
    stat3:           'Tarjetas Compatibles',
    stat4:           'Calificación Promedio',

    // FEATURES SECTION
    feat_title:      'Todo lo que necesitas para tus finanzas',
    feat_sub:        'Funciones poderosas impulsadas por inteligencia artificial',
    f1_title:        'Escáner de Recibos IA',
    f1_desc:         'Fotografía cualquier recibo y nuestra IA detecta automáticamente el monto, categoría, fecha y comercio.',
    f2_title:        'Mejor Tarjeta para Cada Gasto',
    f2_desc:         'Recibe recomendaciones de qué tarjeta usar según los beneficios, cashback y puntos disponibles.',
    f3_title:        'Plan de Pago de Deudas',
    f3_desc:         'Estrategias personalizadas para pagar tus deudas más rápido usando los métodos Avalanche y Snowball.',
    f4_title:        'Asistente Financiero IA',
    f4_desc:         'Pregunta cualquier cosa sobre tus finanzas y recibe consejos personalizados basados en tus datos reales.',
    f5_title:        'Gestión de Suscripciones',
    f5_desc:         'Detecta automáticamente tus suscripciones activas, te alerta antes de cobros y calcula cuánto gastas al mes.',
    f6_title:        'Personal vs Empresa',
    f6_desc:         'Separa automáticamente gastos personales de los del negocio para mantener tus finanzas organizadas.',

    // PRICING SECTION
    price_title:     'Planes y Precios',
    price_sub:       'Comienza gratis, escala cuando estés listo',
    billing_monthly: 'Mensual',
    billing_annual:       'Anual',
    status_active:        'Activa',
    status_due_soon:      'Vence pronto',
    cat_other:            'Otro',
    vip_welcome:          '🌟 ¡Bienvenido a VIP',
    enjoy_benefits:       'Disfruta tus beneficios.',
    cancel_sub:           'Cancelar',
    per_month:            '/mes',
    plan_free_label:      'Free',
    billing_save:    '-20%',
    billing_banner:  '🎉 Pagas anual y ahorras hasta $120/año — 2 meses GRATIS',
    plan_popular:    'Más Popular',
    plan_current:    'Tu plan actual',
    plan_month:      '/mes',
    plan_year:       '/año',
    period_personal: '/mes',
    period_pro:      '/mes',
    period_business: '/mes',
    plan_free_btn:   'Gratis para siempre',
    btn_start_free:  'Empezar Gratis',
    btn_start_now:   '🚀 Empezar ahora',
    btn_want_pro:    '⚡ Quiero Pro',
    feat_unlimited_ai: '✅ IA ilimitada 24/7',
    feat_gpt4o:            '✅ Motor IA GPT-4o',
    feat_unlimited_cards:  '✅ Recomendaciones ilimitadas de tarjetas',
    feat_smart_scanner:    '✅ Escáner inteligente de recibos',
    feat_advanced_reports: '✅ Reportes financieros avanzados',
    feat_ai_goals:         '✅ Metas financieras con IA',
    feat_save_avg:         '✅ Ahorra un 23% en promedio',
    billed_annually:       'Facturado anualmente — ahorra 20%',
    plan_pers_btn:   'Obtener Personal',
    plan_pro_btn:    'Obtener Pro',
    plan_biz_btn:    'Obtener Business',

    // SIDEBAR NAV
    nav_dash:         'Dashboard',
    dash_limit_reached: 'Límite alcanzado:',
    dash_upgrade:       'Actualiza tu plan',
    dash_txs_used:      'transacciones usadas',
    dash_consider_upgrade: 'Considera actualizar tu plan',
    tx_empty:    'No tienes transacciones registradas.',
    tx_no_desc:  'Sin descripción',
    nav_scan:        'Escáner IA',
    nav_trans:       'Transacciones',
    nav_cards:       'Mis Tarjetas',
    nav_debts:       'Deudas',
    nav_subs:        'Suscripciones',
    nav_recs:        'Recomendaciones',
    nav_ai:          'Asistente IA',
    nav_rep:         'Reportes',
    nav_set:         'Configuración',
    nav_logout:      'Cerrar Sesión',

    // DASHBOARD
    dash_title:      'Dashboard',
    dash_sub:        'Resumen financiero de este mes',
    lbl_income:      'Ingresos del Mes',
    lbl_expense:     'Gastos del Mes',
    lbl_balance:     'Balance Disponible',
    lbl_debt:        'Deuda Total',
    lbl_recent:      'Transacciones Recientes',
    btn_logout:      'Cerrar Sesión',
    btn_add:         '+ Agregar',
    btn_view_all:    'Ver todas',

    lbl_subs:        'Suscripciones Activas',
    ai_assistant:    '🤖 Asistente IA',
    badge_online:    'En línea',
    dash_chat_intro: '👋 ¡Hola! Soy tu asistente financiero IA. Este mes has gastado <strong>$2,847.50</strong> y tu balance es positivo. ¿En qué te puedo ayudar?',
    dash_chat_greeting: '¡Hola! Este mes has gastado',
    dash_chat_spent:    'y tu balance es',
    dash_chat_help:     '¿En qué te puedo ayudar?',
    dash_balance_positive: 'positivo.',
    dash_balance_negative: 'negativo.',
    ai_messages_left: '{n}/5 mensajes hoy',
    ph_chat:         'Pregúntame algo sobre tus finanzas...',

    lbl_debts:       'Plan de Deudas',
    btn_view_plan:   'Ver Plan',
    sub_renews:      'Renueva',
    lbl_limit:       'Límite:',
    lbl_used:        'utilizado',

    dash_view_all:   'Ver todas',
    dash_ai_title:   '🤖 Asistente IA',
    dash_ai_online:  'En línea',
    dash_chat_ph:    'Pregúntame algo sobre tus finanzas...',
    dash_vs_last:        'vs mes anterior',
    dash_healthy:        '✓ Finanzas saludables',
    dash_watch:          '⚠️ Controla tus gastos',
    dash_critical:       '🔴 Crítico: Deuda alta',
    dash_debt_month:     '↓ este mes',
    dash_messages_left:  'mensajes hoy',

    // TRANSACTIONS
    trans_title:     'Transacciones',
    trans_add:       'Agregar Transacción',
    trans_all:       'Todas',
    trans_income:    'Ingresos',
    trans_expense:   'Gastos',
    trans_empty:     'Sin transacciones aún',

    // CARDS
    cards_title:     'Mis Tarjetas',
    cards_sub:       'Gestiona tus tarjetas de crédito y débito',
    btn_add_card:    '+ Agregar Tarjeta',
    debts_sub:       'Estrategia personalizada para salir de deudas más rápido',
    btn_add_debt:    '+ Agregar Deuda',
    tab_avalanche:   '❄️ Avalanche (Menos interés)',
    tab_snowball:    '⛄ Snowball (Más motivación)',
    lbl_total_debt:  'Deuda Total',
    lbl_est_time:    'Tiempo Estimado',
    lbl_min_pay:     'Pago Mínimo Total',
    rec_ia_title:    '💡 Recomendaciones IA',

    cards_add:       'Agregar Tarjeta',
    card_healthy:     'Saludable',
    card_warning:     'Precaución',
    card_danger:      'Alto uso',
    card_holder:      'TITULAR',
    card_limit_label: 'LÍMITE',
    card_no_name:     'Sin nombre',
    card_due:         'Vence día',
    cards_personal:   '👤 Tarjetas Personales',
    cards_business:   '🏢 Tarjetas de Empresa',
    card_edit_title:  '✏️ Editar Tarjeta',
    card_name_bank:   'Nombre / Banco',
    card_bank_label:       'Nombre del banco',
    card_bank_placeholder: 'Ej. BBVA, Santander, Nubank...',
    card_type_label:  'Tipo',
    card_limit_lbl:   'Límite ($)',
    card_balance_lbl: 'Balance usado ($)',
    card_last4:       'Últimos 4 dígitos',
    card_apr:         'APR (%)',
    card_color:       'Color de tarjeta',
    card_due_day:     'Día de vencimiento',
    card_name_required: 'El nombre es requerido',
    card_updated:     '✅ Tarjeta actualizada',
    card_save_error:  'Error al guardar cambios',
    card_deleted:     'Tarjeta eliminada',
    card_delete_error:'Error al eliminar tarjeta',
    btn_cancel:       'Cancelar',
    btn_save:         '💾 Guardar Cambios',
    debt_add_title:    '📉 Agregar Deuda',
    debt_name_label:      'Nombre (Tarjeta / Préstamo)',
    debt_name_placeholder:'ej: Chase Visa...',
    debt_balance_label:   'Balance Actual ($)',
    debt_min_label:       'Pago Mínimo Mensual ($)',
    debt_save_btn:        '💾 Guardar Deuda',
    debt_invalid_balance: 'Ingresa un balance válido',
    session_expired:      'Sesión expirada',
    debt_added:           '✅ Deuda agregada!',
    debt_save_error:      'Error al guardar deuda',
    debt_deleted:         'Deuda eliminada',
    debt_delete_error:    'Error al eliminar deuda',
    debts_empty:          'No tienes deudas registradas.',
    debt_priority_high:   'Prioridad ALTA',
    debt_priority_med:    'Prioridad MEDIA',
    debt_priority_low:    'Pago mínimo por ahora',
    debt_used:            'usado',
    debt_of:              'de',
    debt_utilized:        'utilizado',
    debt_min_pay:         'Pago mínimo',
    btn_delete:           'Eliminar',
    debts_personal:       'Deudas Personales',
    debts_business:       'Deudas Empresa',
    time_years:           'años',
    time_months:          'meses',
    method_avalanche:     '❄️ Método Avalanche',
    method_snowball:      '⛄ Método Snowball',
    debt_method_avalanche_desc: '📊 Paga primero la deuda con mayor interés — ahorras más dinero en total',
    debt_method_snowball_desc:  '⛄ Paga primero la deuda más pequeña — genera impulso y motivación',
    toast_avalanche:      '📊 Avalanche: ¡Pagas menos intereses en total!',
    toast_snowball:       '⛄ Snowball: ¡Más motivación para seguir!',
    cards_limit:     'Límite de Crédito',
    cards_used:      'Usado',
    cards_available: 'Disponible',
    cards_empty:     'No hay tarjetas agregadas',

    // DEBTS
    debts_title:     'Deudas',
    debts_total:     'Deuda Total',
    debts_payoff:    'Liquidación Estimada',
    debts_method:    'Método de Pago',
    debts_add:       'Agregar Deuda',
    debt_method_title: '❄️ Método Avalanche',
    debt_ai_recs:    '💡 Recomendaciones IA',

    // SUBSCRIPTIONS
    subs_title:      'Suscripciones',
    debt_score_warn:              'Tu score crediticio está en riesgo. Reducir esta tarjeta por debajo del 30% podría aumentar tu puntaje significativamente.',
    debt_consol_tip:              'Tu APR promedio es peligrosamente alto. Un préstamo personal al 12-15% podría ahorrarte miles — actúa antes de que los intereses sigan creciendo.',
    debt_at:                      'al',
    debt_free_in:                 'Podrías estar completamente libre de deudas en solo',
    debt_save_interest:           'y conservar',
    debt_extra_pay_title:         '✅ Ataca tu deuda con un pago extra:',
    debt_high_flow_title:         '🚀 Tienes poder real para acelerar:',
    debt_high_flow_tip:           'Con {flow} libres cada mes, destinar {suggested} a {card} podría eliminarla en tiempo récord — y liberar aún más efectivo.',
    debt_invest_title:            '📈 Tu flujo de caja abre la puerta a invertir:',
    debt_invest_tip:              'Una vez que elimines tu deuda de alto interés, redirigir {amount}/mes a fondos indexados podría crecer a {projection} en 10 años.',
    debt_free_balance_title:      '💰 Tienes dinero trabajando en tu contra ahora mismo:',
    debt_free_balance_tip:        'Tienes {amount} disponible este mes. Enviar solo {suggested} a {card} hoy podría ahorrarte {interest} en intereses a largo plazo.',
    debt_negative_balance_title:  '🚨 Tus gastos están consumiendo tu futuro:',
    debt_negative_balance_tip:    'Estás gastando más de lo que ganas. Eliminar solo un gasto recurrente podría liberar efectivo para empezar a revertir esto hoy.',
    debt_plan_title:              '📋 Tu plan personalizado para salir de deudas:',
    debt_plan_step1:              'Paso 1 — Paga los mínimos en todas las deudas excepto {card}.',
    debt_plan_step2:              'Paso 2 — Envía cada dólar extra a {card} ({apr}% APR).',
    debt_plan_step3:              'Paso 3 — Una vez pagada {card}, transfiere ese pago a la siguiente deuda.',
    debt_plan_result:             'Siguiendo este plan, podrías estar libre de deudas en {time} y ahorrar {savings} en intereses.',
    subs_sub:        'Gestiona todas tus suscripciones activas',
    btn_add_sub:     '+ Agregar',
    lbl_active_subs: 'Suscripciones Activas',
    lbl_monthly_exp: 'Gasto Mensual',
    lbl_annual_exp:  'Gasto Anual',
    th_service:      'SERVICIO',
    th_price:        'PRECIO',
    th_renewal:      'RENOVACIÓN',
    th_status:       'ESTADO',
    badge_active:    'Activa',
    badge_soon:      'Vence pronto',
    status_active:   'Activa',
    status_due_soon: 'Vence pronto',

    per_month_short: '/mes',
    sub_renews:      'Renueva el día',
    sub_day:         'Día',
    no_subscriptions:'Sin suscripciones aún',
    add_sub_short:   'Agregar una',
    cancel_sub:      'Cancelar',

    subs_total:      'Total Mensual',
    subs_count:      'Suscripciones Activas',
    subs_add:        'Agregar Suscripción',
    subs_empty:      'Sin suscripciones aún',

    // SCANNER
    scan_title:      'Escáner de Recibos IA',
    scan_upload:     'Arrastra tu recibo aquí o haz clic para subir',
    scan_formats:    'Soporta JPG, PNG, PDF',
    scan_analyzing:  'Analizando recibo...',
    scan_merchant:   'Comercio',
    scan_amount:     'Monto',
    scan_date:       'Fecha',
    scan_category:   'Categoría',
    scan_save:       'Guardar Gasto',

    // REPORTS
    rep_title:       'Reportes',
    rep_cat:         '📊 Gastos por Categoría',
    rep_monthly:     '📅 Resumen Mensual 2025',
    reports_title:   '📈 Reportes',
    reports_sub:     'Análisis detallado de tus finanzas',
    btn_csv:         '⬇ CSV',
    btn_pdf:         '⬇ PDF',
    lbl_total_income:'Ingresos Total',
    lbl_total_expense:'Gastos Total',
    lbl_transactions:'Transacciones',
    rep_by_cat:      '📊 Gastos por Categoría',
    th_month:        'MES',
    th_income:       'INGRESOS',
    th_expense:      'GASTOS',
    th_balance:      'BALANCE',
    month_jan:       'Enero',
    month_feb:       'Febrero',
    month_mar:       'Marzo',
    month_apr:       'Abril',
    month_may:       'Mayo',
    month_jun:       'Junio',


    // SETTINGS
    set_title:       'Configuración',
    set_profile:     '👤 Perfil',
    set_subtitle:    'Personaliza tu experiencia',
    lbl_name:        'Nombre',
    lbl_email:       'Email',
    lbl_country:     'País',
    set_currency:    'Moneda',
    set_language:    '🌐 Idioma',
    set_plan:        '💳 Elige tu plan',
    set_notif:       '🔔 Notificaciones',
    set_danger:      '⚠️ Zona de Peligro',
    set_legal:       '⚖️ Legal',
    set_save:        'Guardar Cambios',
    set_logout_all:  'Cerrar Sesión en Todos los Dispositivos',
    set_delete:      'Eliminar Cuenta',

    // GENERAL
    general_save:    'Guardar',
    general_cancel:  'Cancelar',
    general_delete:  'Eliminar',
    general_edit:    'Editar',
    general_add:     'Agregar',
    general_close:   'Cerrar',
    general_loading: 'Cargando...',
    general_yes:     'Sí, eliminar',
    general_personal:'Personal',
    general_business:'Empresa',

    // TOASTS
    toast_saved:     'Guardado exitosamente',
    toast_deleted:   'Eliminado exitosamente',
    toast_error:     'Error. Por favor intenta de nuevo.',

    // UPGRADE MODAL
    upgrade_title:   'Actualiza tu plan',
    upgrade_cta:     'Ver Planes',
    upgrade_cancel:  'Quizás después',

    // LIMIT BANNERS
    limit_reached:   '🚫 Límite alcanzado',
    limit_warning:   '⚠️ usadas — Considera actualizar',
    limit_upgrade:   'Actualiza tu plan',

    // AI CHAT
    ai_welcome:      '👋 ¡Hola! Soy tu asistente financiero IA. ¿En qué te puedo ayudar?',
    ai_placeholder:  'Pregúntame algo sobre tus finanzas...',
    ai_thinking:     '💭 Pensando...',
    ai_msgs_left:    'mensajes hoy',
    debt_saves_interest: 'Pagar la deuda con mayor interés primero te ahorra más dinero a largo plazo.',
    debt_tip_text:       'Paga primero la tarjeta con mayor tasa de interés.',
    credit_score_warn:   'Tu score crediticio puede bajar. Prioriza reducir esta tarjeta primero.',
    badge_vence_pronto:  'Vence pronto',
    rec_based_on:        'Basado en tus transacciones: gastas más en ',
    badge_eval:      '⚠️ Evaluar',
    subs_ia_rec:     '💡 Recomendación IA:',
    subs_ia_desc:    'Xbox Game Pass tiene bajo uso según tus patrones. Cancelarla ahorraría <strong style="color:var(--white);">$179.88/año</strong>.',
    recs_title:      '⭐ Recomendaciones de Tarjetas',
    recs_sub:        'Las mejores tarjetas según tus hábitos de gasto',
    rec_ai_analysis: 'Análisis IA de tus gastos',
    rec_best_general:'USA — MEJOR OPCIÓN GENERAL',
    rec_best_travel: 'USA — MEJOR PARA VIAJES',

    rec_desc_default:    'Disponible en México, Colombia y Brasil. Sin cuotas ocultas, control total desde el app.',
    rec_best_no_fee: 'USA — MEJOR SIN CUOTA',
    rec_latam:       'LATINOAMÉRICA',
    ai_section_title:'🤖 Asistente Financiero IA',
    ai_section_sub:  'Powered by Google Gemini AI',
    ai_online:       '● En línea',
    ai_cap_2:        '• 💳 Recomendar la mejor tarjeta para cada compra',
    ai_cap_3:        '• 📉 Crear un plan para pagar tus deudas',
    ai_cap_4:        '• 💡 Darte consejos personalizados',
    ai_cap_5:        '• 🔄 Detectar suscripciones que podrías cancelar',
    ai_cap_end:      '<br>¿En qué te puedo ayudar hoy?',
    quick_reduce:    '💡 Reducir gastos',
    quick_best_card: '💳 Mejor tarjeta',
    quick_debt_plan: '📉 Plan de deudas',
    quick_subs:      '🔄 Suscripciones',
    btn_send:        'Enviar →',

    no_trans_yet:        'Sin transacciones aún',
    sub_scanner:       'Fotografía tu recibo y la IA detecta todo automáticamente',
    sub_cards:         'Gestiona tus tarjetas de crédito y débito',
    title_rec_ia:      '💡 Recomendaciones IA',
    sub_subs:          'Gestiona todas tus suscripciones activas',
    debt_rec_ia_label: '💡 Recomendación IA:',
    title_card_recs:   '⭐ Recomendaciones de Tarjetas',
    sub_card_recs:     'Las mejores tarjetas según tus hábitos de gasto',
    ai_greeting:       '🤖 ¡Hola! Soy tu asistente financiero personal impulsado por Google Gemini AI.',
    ai_can_help:       'Puedo ayudarte con:',
    ai_cap_1:          '• 📊 Analizar tus gastos e ingresos',
    pf3:             '50 mensajes IA por día',
    pf4:             'Hasta 3 tarjetas',
    pf5:             'Scanner de recibos',
    modal_free_f1:   '✅ 5 mensajes IA por día',
    modal_free_f2:   '✅ Hasta 30 transacciones',
    modal_free_f3:   '✅ 1 tarjeta',
    modal_free_f4:   '❌ Sin scanner de recibos',
    modal_pro_f1:    '✅ 50 mensajes IA por día',
    modal_pro_f2:    '✅ Hasta 3 tarjetas',
    modal_pro_f3:    '✅ Scanner de recibos',
    upgrade_li_scanner: '✅ Scanner de recibos',
    pf1:             'Hasta 50 transacciones/mes',
    pf2:             '1 tarjeta de crédito',
    ai_msgs_today:   '5/5 mensajes hoy',

    // APP.HTML data-key mappings
    dash_dashboard:      'Dashboard',
    dash_receipts:       'Escáner de Recibos',
    dash_transactions:   'Transacciones',
    dash_cards:          'Mis Tarjetas',
    dash_debt:           'Plan de Deudas',
    dash_subscriptions:  'Suscripciones',
    dash_ai:             'Asistente IA',
    dash_settings:       'Configuración',
    dash_welcome:        'Bienvenido de vuelta',
    dash_scan:           'Escanear Recibo',
    dash_income:         'Ingresos del Mes',
    dash_expenses:       'Gastos del Mes',
    dash_balance:        'Balance Total',
    dash_savings:        'Tasa de Ahorro',
    dash_recent:         'Transacciones Recientes',
    dash_quick:          'Acciones Rápidas',
    dash_add:            'Agregar Transacción',
    dash_plan:           'Ver Plan de Deudas',
    dash_recommend:      'Recomendaciones de Tarjetas',
    scan_result:         'Gasto Detectado',
    scan_type:           'Tipo',
    scan_rescan:         'Escanear Otro',
    cards_recommend:     'Mejor Tarjeta Para...',
    debt_title:          'Plan de Pago de Deudas',
    debt_add:            'Agregar Deuda',
    debt_monthly:        'Pago Mensual',
    debt_payoff:         'Liquidación Est.',
    debt_interest:       'Interés Ahorrado',
    debt_method:         'Método de Pago',
    debt_avalanche:      'Avalanche (Mayor Interés Primero)',
    debt_snowball:       'Snowball (Menor Balance Primero)',
    debt_name:           'Nombre de Deuda',
    debt_balance:        'Balance',
    debt_min:            'Pago Mínimo',
    debt_rate:           'Tasa de Interés',
    debt_save:           'Guardar Deuda',
    subs_next:           'Próximo Cobro',
    ai_title:            'Asistente IA',
    ai_suggestions:      'Intenta preguntar:',
    settings_title:      'Configuración',
    settings_profile:    'Perfil',
    settings_currency:   'Moneda',
    settings_language:   'Idioma',
    settings_plan:       'Plan Actual',
    settings_upgrade:    'Actualizar Plan',
    settings_save:       'Guardar Cambios',
    settings_notifications: 'Notificaciones',

    // DYNAMIC MESSAGES
    upgrade_available:      'Disponible desde el plan',
    upgrade_warning:        '🚨 Solo te quedan {n} transacciones — ¡Actualiza ahora!',
    ai_limit_reached:       '🔒 Alcanzaste tu límite de 5 mensajes hoy. ¡Actualiza a VIP para mensajes ilimitados! 🌟',
    ai_limit_daily:         '🔒 Límite diario alcanzado. ¡Actualiza a VIP! 🌟',
    ai_msgs_day:            '5 mensajes IA por día',
    ai_msgs_warning:        '⚠️ Te quedan {n} mensajes IA hoy — considera actualizar tu plan',
    trans_empty_cat:        'No tienes transacciones en esta categoría.',
    trans_export_empty:     'No hay transacciones para exportar aún — ¡agrega algunas!',
    export_filename:        'financeai_transacciones',
    credit_limit:           'Límite de crédito',

    // TOASTS & DYNAMIC UI
    subs_invalid_amount:    'Ingresa un monto válido',
    subs_save_error:        'Error al guardar suscripción',
    subs_deleted:           'Suscripción eliminada',
    subs_delete_error:      'Error al eliminar suscripción',
    plan_vip_sub:           'Mensajes ilimitados · Vence en {n} días',
    plan_free:              'Gratuito',
    plan_free_forever:      'Gratis para siempre',
    plan_current:           'Tu plan actual',
    plan_current_free:      'Tu plan actual — Gratis',
    plan_expires:           'Vence en {n} días',
    plan_actual:            'Plan actual:',
    current_plan_badge:     '✨ Tu plan actual:',
    receipt_scanned:        'Recibo escaneado',
    btn_save_card:          'Guardar',
    scan_requires_plan:     'El Scanner requiere plan Personal o superior',
    pay_with_card:          '💳 Pagar con Tarjeta (Stripe)',
    secure_payment:         '🔒 Pago seguro con Stripe',
    payment_failed:         'Pago fallido. Por favor intenta de nuevo.',
    loading_paypal:         'Cargando PayPal...',
    payment_cancelled:      'Pago cancelado.',
    try_again:              'Intentar de nuevo',
    could_not_load_paypal:  'No se pudo cargar PayPal. Usa pago con tarjeta.',
    could_not_load_sdk:     'No se pudo cargar el SDK de PayPal.',
    payment_success:        '¡Pago Exitoso!',
    welcome_pro:            'Bienvenido a FinanceAI Pro',
    redirecting_dashboard:  'Redirigiendo al panel...',
    processing:             'Procesando...',
    upgrade_required:       'Actualización Requerida',
    requires_plan:          'requiere el plan',
    plan_or_higher:         'o superior.',
    maybe_later:            'Quizás Después',
    upgrade_now:            'Actualizar Ahora',
    scan_unknown:           'Desconocido',
    scan_other:             'Otro',
    scan_error:             'Error al analizar el recibo. Intenta con otra imagen.',
    scan_no_data:           'No hay datos del recibo para guardar',
    scan_save_error:        'Error al guardar la transacción',
    scan_read_error:        'No pudimos leer ese recibo — intenta con mejor iluminación 📸',
    scan_first:             'Escanea un recibo primero para guardarlo 📸',
    scan_save_error2:       'Error al guardar — intenta de nuevo en un momento',
    pdf_ready:              '✅ PDF listo — usa "Guardar como PDF" en el diálogo de impresión 🎉',
    card_name_required:     'Ingresa el nombre del titular',
    card_save_error:        'Error al guardar tarjeta',
    // AUTH
    sign_in:                'Iniciar Sesión',
    error_password_length:  'La contraseña debe tener al menos 6 caracteres',
    please_enter_credentials: 'Por favor ingresa email y contraseña',
    fill_all_fields:          'Por favor completa todos los campos',
    account_created:          '¡Cuenta creada! Revisa tu email para verificar tu cuenta.',
    enter_email_first:        'Ingresa tu email primero',
    password_reset_sent:      '¡Email de restablecimiento enviado! Revisa tu bandeja.',
    ai_proxy_ready:   'OpenAI proxy listo via Supabase Edge Function',
    messages_vip:     '∞ mensajes (VIP)',
    messages_today:   ' mensajes hoy',
    plan_label:              'Plan:',
    amount_label:            'Monto:',
    could_not_create:        'No se pudo crear la sesión de pago',
    paypal_failed:           'Pago con PayPal fallido. Por favor intenta de nuevo.',
    plan_personal_price:     'Personal ($9.99/mes)',
    plan_pro_price:          'Pro ($19.99/mes)',
    plan_business_price:     'Business ($49.99/mes)',
    subs_added:              '✅ ¡Suscripción agregada!',
    subs_detected:           '💡 Suscripción detectada: ',
    code_generated:          'generado',
    code_copied_clipboard:   '📋 Código copiado al portapapeles',
    code_copied:             '📋 Copiado',
    login_required:          '⚠️ Inicia sesión para continuar',
    processing_payment:      '🔒 Procesando',
    redirecting_stripe:      '🚀 ¡Redirigiendo al pago seguro con Stripe!',
    stripe_session_error:    '❌ Error al crear sesión de pago — intenta de nuevo',
    connection_error:        '❌ Error de conexión — verifica tu internet',
    transaction_saved:       '✅ Transacción guardada correctamente',
    scanner_unlock:          '✨ Desbloquea el Scanner IA — ahorra horas cada semana',
    receipt_detected:        '🎯 ¡Recibo detectado! Revisa los datos y guarda en 1 click',
    saved_history:           '✅ ¡Guardado! Tu historial financiero se actualiza automáticamente 🚀',
    export_requires_pro:     '📤 Exportar requiere plan Pro — ¡lleva tus finanzas al siguiente nivel!',
    code_label:              'Código',
    months_label:            'mes(es)',
    no_codes_generated:      'No hay códigos generados aún',
    no_codes_activated:      'Ningún código activado aún',
    scanning_receipt:        'Analizando recibo con IA...',
    ai_reading_receipt:      'Tu IA está leyendo el recibo...',
    ai_reading_seconds:      'Esto solo toma unos segundos',
    receipt_analyzed:        '¡Recibo analizado exitosamente!',
    receipt_analyzed_ok:     'Recibo analizado correctamente',
    scan_again:              'Click para escanear otro recibo',
    upload_receipt_title:    'Subir Foto del Recibo',
    upgrade_social_proof:    '⚡ Miles de usuarios ya controlan sus finanzas con esto',
    upgrade_one_step:        'Estás a 1 paso de tener control total de tu dinero 💡',
    upgrade_unlock_btn:      '🔓 Desbloquear Ahora — Ver Planes',
    upgrade_dismiss:         'No, prefiero seguir perdiendo dinero sin saberlo',
    no_transactions:         'No tienes transacciones registradas.',
    no_description:          'Sin descripción',
    no_subscriptions:        'No tienes suscripciones.',
    add_sub_short:           '+ Agregar',
    per_month_short:         '/mes',
    add_sub_title:           '🔄 Agregar Suscripción',
    sub_name_label:          'Nombre del Servicio',
    sub_amount_label:        'Monto Mensual ($)',
    ai_analyzing:            '⏳ Analizando...',
    ai_connect_error:        '❌ Error al conectar con IA. Intenta de nuevo.',
    upgrade_limited_offer:   '⚡ Oferta limitada — Solo hoy',
    upgrade_losing_money:    'Estás perdiendo dinero<br>sin saberlo',
    upgrade_ai_limit_desc:   'Alcanzaste tu límite de IA gratuita. Los usuarios Pro detectan gastos ocultos y ahorran en promedio <strong style="color:#f59e0b;">$340 al mes</strong>. ¿Cuánto estás perdiendo tú?',
    upgrade_unlock_all:      '🔓 Desbloquea todo ahora:',
    upgrade_feat_ai:         '<strong>IA ilimitada 24/7</strong> — tu asesor financiero personal siempre disponible',
    upgrade_feat_gpt4:       '<strong>GPT-4o</strong> — detecta patrones de gasto que tú no ves',
    upgrade_feat_scanner:    '<strong>Scanner inteligente</strong> — registra recibos en 2 segundos',
    upgrade_feat_reports:    '<strong>Reportes que te hacen ahorrar</strong> — ve exactamente dónde va tu dinero',
    upgrade_feat_goals:      '<strong>Metas con IA</strong> — alcanza libertad financiera más rápido',
    upgrade_real_value:      'Valor real: $29.99/mes',
    upgrade_today_get:       'Hoy lo obtienes por',
    upgrade_cancel_anytime:  '✅ Cancela cuando quieras · Sin contratos',
    upgrade_annual_deal:     '💰 Mejor deal: Plan anual — Ahorra 40%',
    upgrade_social_proof2:   '⭐⭐⭐⭐⭐ <strong style="color:#fff;">+1,200 usuarios</strong> ya toman control de su dinero',
    upgrade_testimonial:     '"Recuperé $180 el primer mes detectando suscripciones olvidadas" — María G.',
    upgrade_no_thanks:       'No me interesa ahorrar dinero ahora mismo',
    code_status_used:        '✅ Usado',
    code_status_pending:     '⏳ Pendiente',
    code_status_activated:   '✅ Activado',
    ai_no_response:          '❌ Sin respuesta',
    ai_system_prompt:        'Eres un asistente financiero personal inteligente llamado FinanceAI. Ayudas a los usuarios a entender sus finanzas, dar consejos de ahorro, analizar gastos y más. Responde siempre en el idioma que use el usuario (español o inglés). Sé conciso, amigable y útil. Máximo 3 párrafos.',
    price_suffix_monthly:    '/mes',
    price_suffix_annual:     '/mes (anual)',
    scan_error_image:        'Error al analizar imagen',
    scan_error_extract:      'No se pudo extraer información del recibo',
    scan_prompt_categories:  'Supermercado, Restaurante, Gasolina, Farmacia, Ropa, Entretenimiento, Transporte, Servicios, Otro',
    scan_cat_supermarket:    'Supermercado',
    scan_cat_restaurant:     'Restaurante',
    scan_cat_gas:            'Gasolina',
    scan_cat_pharmacy:       'Farmacia',
    scan_cat_clothing:       'Ropa',
    scan_cat_entertainment:  'Entretenimiento',
    scan_cat_transport:      'Transporte',
    scan_cat_services:       'Servicios',
    scan_cat_other:          'Otro',
    csv_header_date:         'Fecha',
    csv_header_desc:         'Descripción',
    csv_header_cat:          'Categoría',
    csv_header_amount:       'Monto',
    csv_header_type:         'Tipo',
    csv_downloaded:          '✅ CSV descargado — ábrelo en Excel o Google Sheets 🎉',
    pdf_title:               'FinanceAI Pro — Reporte Financiero',
    pdf_generated:           'Reporte generado:',
    pdf_transactions:        'Transacciones',
    pdf_footer:              'Generado por FinanceAI Pro · climberforsuccess.online',
    month_jan: 'Enero',      month_feb: 'Febrero',    month_mar: 'Marzo',
    month_apr: 'Abril',      month_may: 'Mayo',       month_jun: 'Junio',
    month_jul: 'Julio',      month_aug: 'Agosto',     month_sep: 'Septiembre',
    month_oct: 'Octubre',    month_nov: 'Noviembre',  month_dec: 'Diciembre',
    worst_month_badge:       '📛 más gastos',
    optimize_cta:            '⚡ Optimiza →',
    last_updated:            'Última actualización:',
    nav_cookies:             '🍪 Cookies',
    btn_close:               '✖ Cerrar',
    legal_cancel_anytime:    'Puede cancelar en cualquier momento desde su portal de cliente',
    card_modal_title:        '💳 Nueva Tarjeta',
    card_holder_label:       'Nombre del titular',
    card_holder_placeholder: 'Ej: Juan Pérez',
    card_type_label:         'Tipo de tarjeta',
    card_usage_label:        'Uso de la tarjeta',
    card_usage_personal:     '👤 Personal',
    card_usage_business:     '🏢 Empresa',
    card_saved_ok:           '✅ Tarjeta guardada',
    tx_label_desc:           'Descripción',
    tx_placeholder_desc:     'Ej: Salario, Supermercado...',
    tx_label_amount:         'Monto',
    tx_label_type:           'Tipo',
    tx_opt_expense:          'Gasto',
    tx_opt_income:           'Ingreso',
    tx_label_owner:          '¿Es personal o de empresa?',
    tx_opt_personal:         'Personal',
    tx_opt_business:         'Empresa',
    tx_label_category:       'Categoría',
    tx_label_date:           'Fecha',
    tx_alert_required:       'Por favor completa descripción, monto y fecha.',
    tx_alert_error:          'Error al guardar: ',
    tx_confirm_delete:       '¿Estás seguro de que deseas eliminar esta transacción?',
    notif_tx_deleted:        'Transacción eliminada correctamente',
    ctx_total_income:        '- Ingresos totales',
    ctx_total_expense:       '- Gastos totales',
    ctx_net_balance:         '- Balance neto',
    ctx_total_debt:          '- Deuda total',
    ctx_cards:               '- Tarjetas',
    ctx_subscriptions:       '- Suscripciones',
    ctx_plan:                '- Plan',
    cat_productivity:        'Productividad',
    cat_storage:             'Almacenamiento',
    cat_shopping:            'Compras',
    cat_gaming:              'Juegos',
    cat_fitness:             'Fitness',
    cat_other:               'Otro',
  }
};

// ===========================
// ID → KEY MAP (complete)
// ===========================
const ID_KEY_MAP = {
  // NAVBAR
  'modal-title':                    'modal_title',
  'landing-original-pro':           'landing_original_pro',
  'landing-original-business':      'landing_original_business',
  'landing-original-personal':      'landing_original_personal',
  'nav-features':                   'nav_features',
  'nav-pricing':       'nav_pricing',
  'nav-login':         'nav_login',
  'nav-start':         'nav_start',

  // HERO
  'hero-badge':        'hero_badge',
  'hero-title':        'hero_title',
  'hero-desc':         'hero_desc',
  'hero-cta':          'hero_cta',
  'hero-demo':              'hero_demo',
  'landing-btn-monthly-label': 'landing_btn_monthly',
  'landing-btn-annual-label':  'landing_btn_annual',
  'landing-savings-text':      'landing_savings_banner',
  'stat1':             'stat1',
  'stat2':             'stat2',
  'stat3':             'stat3',
  'stat4':             'stat4',

  // FEATURES
  'feat-title':        'feat_title',
  'feat-sub':          'feat_sub',
  'f1-title':          'f1_title',
  'f1-desc':           'f1_desc',
  'f2-title':          'f2_title',
  'f2-desc':           'f2_desc',
  'f3-title':          'f3_title',
  'f3-desc':           'f3_desc',
  'f4-title':          'f4_title',
  'f4-desc':           'f4_desc',
  'f5-title':          'f5_title',
  'f5-desc':           'f5_desc',
  'f6-title':          'f6_title',
  'f6-desc':           'f6_desc',

  // PRICING
  'price-title':       'price_title',
  'price-sub':         'price_sub',
  'period-personal':   'period_personal',
  'period-pro':        'period_pro',
  'period-business':   'period_business',

  // SIDEBAR NAV
  'nav-dash':          'nav_dash',
  'nav-scan':          'nav_scan',
  'nav-trans':         'nav_trans',
  'nav-cards':         'nav_cards',
  'nav-debts':         'nav_debts',
  'nav-subs':          'nav_subs',
  'nav-recs':          'nav_recs',
  'nav-ai':            'nav_ai',
  'nav-rep':           'nav_rep',
  'nav-set':           'nav_set',

  // DASHBOARD
  'dash-title':        'dash_title',
  'dash-sub':          'dash_sub',
  'lbl-income':        'lbl_income',
  'lbl-expense':       'lbl_expense',
  'lbl-balance':       'lbl_balance',
  'pf1':               'pf1',
  'pf2':               'pf2',
  'aiMessagesLeft':    'ai_msgs_today',
  'debt-tip-text':      'debt_tip_text',
  'credit-score-warn':  'credit_score_warn',
  'badge-vence-pronto': 'badge_vence_pronto',
  'rec-based-on':       'rec_based_on',
  'rec-desc-default':   'rec_desc_default',
  'no-trans-yet':       'no_trans_yet',
  'pf3':               'pf3',
  'pf4':               'pf4',
  'pf5':               'pf5',
  'modal-free-f1':     'modal_free_f1',
  'modal-free-f2':     'modal_free_f2',
  'modal-free-f3':     'modal_free_f3',
  'modal-free-f4':     'modal_free_f4',
  'modal-pro-f1':      'modal_pro_f1',
  'modal-pro-f2':      'modal_pro_f2',
  'modal-pro-f3':      'modal_pro_f3',
  'upgrade-li-scanner':'upgrade_li_scanner',
  'sub-scanner':       'sub_scanner',
  'sub-cards':         'sub_cards',
  'title-rec-ia':      'title_rec_ia',
  'sub-subs':          'sub_subs',
  'debt-rec-ia-label': 'debt_rec_ia_label',
  'title-card-recs':   'title_card_recs',
  'sub-card-recs':     'sub_card_recs',
  'ai-cap-1':          'ai_cap_1',
  'current-plan-label':  'current_plan_label',
  'pricing-tagline':     'pricing_tagline',
  'plan-free-name':      'plan_free_name',
  'plan-free-period':    'plan_free_period',
  'modal-free-f5':       'modal_free_f5',
  'modal-free-f6':       'modal_free_f6',
  'btn-free-label':      'btn_free_label',
  'vip-status-label':    'vip_status_label',
  'vip-plan-name':       'vip_plan_name',
  'billing-monthly-label': 'billing_monthly',
  'billing-annual-label':  'billing_annual',
  'annual-savings-text': 'annual_savings_text',
  'plan-personal-name':  'plan_personal_name',
  'modal-personal-f1':   'modal_personal_f1',
  'modal-personal-f2':   'modal_personal_f2',
  'modal-personal-f3':   'modal_personal_f3',
  'cta-personal-label':  'cta_personal_label',
  'badge-popular':       'badge_popular',
  'notif-label-4':       'notif_label_4',
  'danger-zone-title':   'danger_zone_title',
  'delete-account-btn-label': 'delete_account_btn',
  'legal-title':         'legal_title',
  'legal-terms-title':   'legal_terms_title',
  'legal-terms-desc':    'legal_terms_desc',
  'legal-privacy-title': 'legal_privacy_title',
  'legal-privacy-desc':  'legal_privacy_desc',
  'copyright-text':      'copyright_text',
  'admin-page-title':    'admin_page_title',
  'admin-page-subtitle': 'admin_page_subtitle',
  'admin-label-total-users': 'admin_label_total',
  'admin-label-vip-users':   'admin_label_vip',
  'admin-label-codes':         'admin_label_codes',
  'admin-label-ai-calls':      'admin_label_ai_calls',
  'admin-vip-mgmt-title':      'admin_vip_mgmt_title',
  'admin-gen-code-label':      'admin_gen_code_label',
  'admin-opt-personal':        'admin_opt_personal',
  'admin-opt-familia':         'admin_opt_familia',
  'admin-opt-1m':              'admin_opt_1m',
  'admin-opt-3m':              'admin_opt_3m',
  'admin-opt-6m':              'admin_opt_6m',
  'admin-opt-12m':             'admin_opt_12m',
  'admin-gen-code-btn-label':  'admin_gen_code_btn',
  'admin-code-generated-label':'admin_code_generated_label',
  'admin-copy-btn-label':      'admin_copy_btn',
  'admin-session-codes-label': 'admin_session_codes',
  'admin-no-codes-msg':        'admin_no_codes_msg',
  'debt-consol-title':         'debt_consol_title',
  'debt-balance-title':        'debt_balance_title',
  'btn-apply':                 'btn_apply',
  'vip-code-input':            'vip_code_placeholder',
  'admin-vip-input':           'admin_vip_placeholder',
  'notif-coming-soon':         'notif_coming_soon',
  'admin-used-codes-title':    'admin_used_codes_title',
  'admin-loading-msg':         'admin_loading_msg',
  'admin-activate-vip-title':  'admin_activate_vip',
  'vip-status-sub-text':       'vip_status_sub_text',
  'admin-vip-enter-label':     'admin_vip_enter_label',
  'activate-vip-btn-label':    'activate_vip_btn',
  'or-buy-plan-label':         'or_buy_plan',
  'vip-personal-name':         'vip_personal_name',
  'vip-personal-badge':        'vip_personal_badge',
  'vip-personal-f1':           'vip_personal_f1',
  'vip-personal-f2':           'vip_personal_f2',
  'vip-personal-f4':           'vip_personal_f4',
  'get-vip-personal-btn':      'get_vip_personal',
  'vip-familia-name':          'vip_familia_name',
  'vip-familia-f1':            'vip_familia_f1',
  'vip-familia-f2':            'vip_familia_f2',
  'vip-familia-f3':            'vip_familia_f3',
  'vip-familia-f4':            'vip_familia_f4',
  'get-vip-familia-btn':       'get_vip_familia',
  'legal-back-btn':            'legal_back_btn',
  'modal-upgrade-title':       'modal_upgrade_title',
  'btn-monthly-label':         'btn_monthly_label',
  'btn-annual-label':          'btn_annual_label',
  'btn-annual-save':           'btn_annual_save',
  'tab-stripe-label':          'tab_stripe',
  'tab-paypal-label':          'tab_paypal',
  'modal-secure-text':         'modal_secure',
  'feat-unlimited-tx':         'feat_unlimited_tx',
  'feat-basic-reports':        'feat_basic_reports',
  'feat-all-pro':              'feat_all_pro',
  'feat-5-users':              'feat_5_users',
  'feat-admin-panel':          'feat_admin_panel',
  'feat-biz-reports':          'feat_biz_reports',
  'feat-support-247':          'feat_support_247',
  'lbl-login-pass':            'lbl_login_pass',
  'lbl-reg-name':              'lbl_reg_name',
  'lbl-reg-plan':              'lbl_reg_plan',
  'nav-admin-label':           'nav_admin_label',
  'scan-tip-1':                'scan_tip_1',
  'scan-tip-2':                'scan_tip_2',
  'scan-tip-3':                'scan_tip_3',
  'scan-tip-4':                'scan_tip_4',
  'plan-pro-name':       'plan_pro_name',
  'plan-pro-real-price': 'plan_pro_real_price',
  'pro-f1':              'pro_f1',
  'pro-f2':              'pro_f2',
  'pro-f3':              'pro_f3',
  'pro-f4':              'pro_f4',
  'pro-f5':              'pro_f5',
  'pro-f6':              'pro_f6',
  'pro-f7':              'pro_f7',
  'cta-pro-label':       'cta_pro_label',
  'pro-cancel-note':     'pro_cancel_note',
  'plan-business-name':  'plan_business_name',
  'biz-f1':              'biz_f1',
  'biz-f2':              'biz_f2',
  'biz-f3':              'biz_f3',
  'biz-f4':              'biz_f4',
  'biz-f5':              'biz_f5',
  'biz-f6':              'biz_f6',
  'biz-f7':              'biz_f7',
  'biz-f8':              'biz_f8',
  'cta-business-label':  'cta_business_label',
  'testimonial-quote':   'testimonial_quote',
  'testimonial-author':  'testimonial_author',
  'vip-code-label':      'vip_code_label',
  'notif-label-1':       'notif_label_1',
  'notif-label-2':       'notif_label_2',
  'notif-label-3':       'notif_label_3',
  'vip-status-sub':    'ai_msgs_day',
  'lbl-debt':          'lbl_debt',
  'lbl-recent':        'lbl_recent',
  'lbl-subs':          'lbl_subs',
  'lbl-debts':         'lbl_debts',
  'debt-method-title': 'debt_method_title',
};

// ===========================
// LANGUAGE STATE
// ===========================
let currentLang = localStorage.getItem('financeai_lang') || 'en';

// ===========================
// t() — get translation
// ===========================
function t(key) {
  return (TRANSLATIONS[currentLang] && TRANSLATIONS[currentLang][key])
    || (TRANSLATIONS['en'] && TRANSLATIONS['en'][key])
    || key;
}

// ===========================
// applyLanguage — full DOM
// ===========================
function applyLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('financeai_lang', lang);
  document.documentElement.lang = lang;

  // 1. ID_KEY_MAP
  Object.entries(ID_KEY_MAP).forEach(([id, key]) => {
    const el = document.getElementById(id);
    if (el) el.innerHTML = t(key);
  });

  // 2. data-i18n attributes
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (key) el.innerHTML = t(key);
  });

  // 2b. data-key attributes (legacy support)
  document.querySelectorAll('[data-key]').forEach(el => {
    const key = el.getAttribute('data-key');
    if (key) el.innerHTML = t(key);
  });

  // 3. data-i18n-placeholder
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (key) el.placeholder = t(key);
  });

  // 4. Logout buttons
  document.querySelectorAll('[data-i18n-logout]').forEach(btn => {
    btn.textContent = t('nav_logout');
  });

  // 5. Lang button active state
  document.querySelectorAll('.lang-btn').forEach(btn => {
    const onclick = btn.getAttribute('onclick') || '';
    btn.classList.toggle('active', onclick.includes(`'${lang}'`));
  });

  // 6. Dispatch event for app.js dynamic content
  // Fire FIRST so renders happen, then re-translate below
  window.dispatchEvent(new CustomEvent('langChanged', { detail: { lang } }));

  // 7. Re-apply data-i18n AFTER dynamic renders
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (key) el.innerHTML = t(key);
  });
}

// ===========================
// setLang — public API
// ===========================
function setLang(lang) {
  applyLanguage(lang);
}

// ===========================
// toggleLang
// ===========================
function toggleLang() {
  setLang(currentLang === 'en' ? 'es' : 'en');
}


// ===========================
// Inicializar idioma al cargar
// ===========================
document.addEventListener('DOMContentLoaded', () => {
  applyLanguage(currentLang);
});
