'use client';

import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

export type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const translations: Record<Language, Record<string, string>> = {
  es: {
    dashboard: 'Dashboard',
    transactions: 'Transacciones',
    myCards: 'Mis Tarjetas',
    debtPlan: 'Salir de Deudas',
    subscriptions: 'Suscripciones',
    recommendations: 'Recomendaciones',
    aiAssistant: 'Asistente IA',
    reports: 'Reportes',
    settings: 'Configuración',
    scannerReceipt: 'Escanear Recibo',
    totalBalance: 'Balance Total',
    monthlyIncome: 'Ingresos Mensuales',
    monthlyExpenses: 'Gastos Mensuales',
    totalDebt: 'Deuda Total',
    savings: 'Ahorros',
    recentTransactions: 'Transacciones Recientes',
    addCard: 'Agregar Tarjeta',
    viewAll: 'Ver Todo',
    noTransactions: 'Sin transacciones',
    date: 'Fecha',
    merchant: 'Comercio',
    category: 'Categoría',
    amount: 'Monto',
    card: 'Tarjeta',
    exportPDF: 'Exportar PDF',
    exportCSV: 'Exportar CSV',
    search: 'Buscar',
    filter: 'Filtrar',
    month: 'Mes',
    year: 'Año',
    cardName: 'Nombre de Tarjeta',
    bank: 'Banco',
    type: 'Tipo',
    balance: 'Balance',
    limit: 'Límite',
    paymentDueDate: 'Fecha de Pago',
    debit: 'Débito',
    credit: 'Crédito',
    personal: 'Personal',
    business: 'Negocio',
    apr: 'APR',
    noCards: 'Sin tarjetas',
    totalDebtAmount: 'Deuda Total',
    debtStrategy: 'Estrategia de Pago',
    estimatedPayoffTime: 'Tiempo Estimado de Pago',
    monthlyPayment: 'Pago Mensual',
    interestRate: 'Tasa de Interés',
    debtType: 'Tipo de Deuda',
    mortgage: 'Hipoteca',
    autoLoan: 'Préstamo de Auto',
    creditCard: 'Tarjeta de Crédito',
    personalLoan: 'Préstamo Personal',
    other: 'Otro',
    avalanche: 'Avalanche',
    snowball: 'Snowball',
    consolidation: 'Consolidación',
    hybrid: 'Híbrido',
    addDebt: 'Agregar Deuda',
    thisMonth: 'Este Mes',
    saved: 'Ahorrado',
    variation: 'Variación',
    food: 'Alimentos',
    transport: 'Transporte',
    income: 'Ingresos',
    entertainment: 'Entretenimiento',
    health: 'Salud',
    salaryPayment: 'Pago de Salario',
    wholeFoodsMarket: 'Whole Foods Market',
    uber: 'Uber',
    netflix: 'Netflix',
    pharmacyCVS: 'Farmacia CVS',
    incomeVsExpenses: 'Ingresos vs Gastos',
    january: 'Ene',
    february: 'Feb',
    march: 'Mar',
    april: 'Abr',
    may: 'May',
    expenses: 'Gastos',
    activeDebt: 'Deuda Activa',
    cards: 'Tarjetas',
    averageInterest: 'Interés Promedio',
    debtObjective: 'Objetivo de Deuda',
    method: 'Método',
    timeline: 'Tiempo',
    months: 'meses',
    incomeLabel: 'Ingresos',
    expensesLabel: 'Gastos',
    balanceLabel: 'Balance',
    previous: 'Anterior',
    next: 'Siguiente',
    page: 'Página',
    of: 'de',
    shopping: 'Compras',
    foodDrink: 'Comida y Bebida',
    groceries: 'Abarrotes',
    transportation: 'Transporte',
    dining: 'Restaurantes',
    gymMembership: 'Membresía de Gimnasio',
    amazon: 'Amazon',
    starbucks: 'Starbucks',
    salaryDeposit: 'Depósito de Salario',
    wholefiles: 'Whole Foods',
    restaurant: 'Restaurante',
    cards_singular: 'tarjeta',
    cards_plural: 'tarjetas',
    totalCreditDebt: 'Deuda Total (Crédito)',
    totalLimit: 'Límite Total',
    utilization: 'Utilización',
    yourCards: 'Tus Tarjetas',
    cardDetails: 'Detalles de Tarjetas',
    edit: 'Editar',
    delete: 'Eliminar',
    utilizationHeader: 'Utilización',
    activeDebts: 'deudas activas',
    highestInterestRate: 'Tasa Más Alta',
    chooseStrategy: 'Elige tu Estrategia',
    strategyDetails: 'Detalles de',
    advantage: 'Ventaja',
    disadvantage: 'Desventaja',
    timeToPayoff: 'Tiempo para Pagar',
    totalEstimatedInterest: 'Interés Total Estimado',
    paymentOrder: 'Orden de Pago',
    order: 'Orden',
    debt: 'Deuda',
    rate: 'Tasa',
    monthlyPaymentHeader: 'Pago Mensual',
    timeHeader: 'Tiempo',
    years: 'años',
    subscription_singular: 'suscripción activa',
    subscription_plural: 'suscripciones activas',
    monthlyCost: 'Costo Mensual',
    activeSubscriptions: 'Suscripciones Activas',
    potentialSavings: 'Ahorro Potencial',
    cancelEntertainment: 'Si cancelas entretenimiento',
    filterByCategory: 'Filtrar por categoría',
    yourSubscriptions: 'Tus Suscripciones',
    monthly: 'Mensual',
    yearly: 'Anual',
    nextPayment: 'Próximo pago',
    cancel: 'Cancelar',
    noSubscriptionsCategory: 'No hay suscripciones en esta categoría',
    upcomingPayments: 'Próximos Pagos',
    subscription: 'Suscripción',
    nextBillingDate: 'Próximo Pago',
    action: 'Acción',
    in: 'En',
    days: 'días',
    aiRecommendations: 'Recomendaciones de IA',
    consolidateStreaming: 'Consolidar Streaming',
    consolidateStreamingDesc: 'Detectamos que tienes 2 servicios de streaming. Considera usar solo uno para ahorrar $20/mes.',
    adobeAlternative: 'Adobe Creative Cloud',
    adobeAlternativeDesc: 'Es tu suscripción más cara. Considera alternativas como Figma o Canva.',
    optimalSpending: 'Gasto Óptimo',
    optimalSpendingDesc: 'Tu gasto total es {monthly}/mes ({percentage}% de ingresos)',
    underControl: 'Está bajo control',
    yearlyTotal: '/año',
    inCategory: 'en',
    all: 'Todos',
    scanReceiptSubtitle: 'Escanea recibos para agregar transacciones automáticamente',
    processing: 'Procesando recibo...',
    analyzingOCR: 'Analizando imagen con OCR',
    clickToUpload: 'Haz clic para cargar un recibo',
    dragOrUpload: 'O arrastra una imagen aquí (JPG, PNG, HEIC)',
    scannedReceipts: 'Recibos Escaneados',
    receiptAmount: 'Monto',
    receiptCard: 'Tarjeta',
    add: 'Agregar',
    discard: 'Descartar',
    info: 'Información',
    supportsFormats: 'Soportamos JPG, PNG, HEIC y otros formatos de imagen',
    extractsAutomatically: 'Extrae automáticamente: comercio, monto, fecha y hora',
    detectsCardDigits: 'Detecta el último dígito de tu tarjeta',
    assignsCategory: 'Asigna categoría automáticamente',
    addsTransaction: 'Agregará la transacción a tu historial',
    at: 'a las',
    settingsTitle: 'Configuración',
    manageAccount: 'Administra tu cuenta y preferencias',
    accountTab: 'Cuenta',
    notificationsTab: 'Notificaciones',
    privacyTab: 'Privacidad',
    currentPlan: 'Plan Actual',
    yourCurrentPlan: 'Tu plan actual',
    financeAIProPlan: 'FinanceAI Pro',
    renewalDate: 'Renovación el 15 de septiembre, 2026',
    cancelSubscription: 'Cancelar Suscripción',
    changePlan: 'Cambiar Plan',
    perMonth: '/mes',
    currentPlanButton: 'Plan Actual',
    language: 'Idioma',
    accountSection: 'Cuenta',
    emailLabel: 'Email',
    changePassword: 'Cambiar Contraseña',
    legalSection: 'Legal',
    termsOfService: 'Términos de Servicio',
    privacyPolicy: 'Política de Privacidad',
    legalTerms: 'Términos Legales',
    planFree: 'Gratis',
    planPersonal: 'Personal',
    planPro: 'Pro',
    planBusiness: 'Business',
    featureBasicDashboard: 'Dashboard básico',
    featureLimitedTx: '5 transacciones/mes',
    featureNoAI: 'Sin IA',
    featureCompleteDashboard: 'Dashboard completo',
    featureUnlimitedTx: 'Transacciones ilimitadas',
    featureBasicAI: 'Asistente IA básico',
    featureScanReceipts: 'Scanner de recibos',
    featureEverythingPersonal: 'Todo de Personal',
    featureAdvancedAI: 'IA avanzada',
    featureExpenseAnalysis: 'Análisis de gastos',
    featureExportPDF: 'Exportación PDF/CSV',
    featureEverythingPro: 'Todo de Pro',
    featureMultiProfiles: '5 perfiles',
    featurePrioritySupport: 'Soporte prioritario',
    featureAPIAccess: 'API access',
  },
  en: {
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    myCards: 'My Cards',
    debtPlan: 'Debt Plan',
    subscriptions: 'Subscriptions',
    recommendations: 'Recommendations',
    aiAssistant: 'AI Assistant',
    reports: 'Reports',
    settings: 'Settings',
    scannerReceipt: 'Scan Receipt',
    totalBalance: 'Total Balance',
    monthlyIncome: 'Monthly Income',
    monthlyExpenses: 'Monthly Expenses',
    totalDebt: 'Total Debt',
    savings: 'Savings',
    recentTransactions: 'Recent Transactions',
    addCard: 'Add Card',
    viewAll: 'View All',
    noTransactions: 'No transactions',
    date: 'Date',
    merchant: 'Merchant',
    category: 'Category',
    amount: 'Amount',
    card: 'Card',
    exportPDF: 'Export PDF',
    exportCSV: 'Export CSV',
    search: 'Search',
    filter: 'Filter',
    month: 'Month',
    year: 'Year',
    cardName: 'Card Name',
    bank: 'Bank',
    type: 'Type',
    balance: 'Balance',
    limit: 'Limit',
    paymentDueDate: 'Payment Due Date',
    debit: 'Debit',
    credit: 'Credit',
    personal: 'Personal',
    business: 'Business',
    apr: 'APR',
    noCards: 'No cards',
    totalDebtAmount: 'Total Debt',
    debtStrategy: 'Payment Strategy',
    estimatedPayoffTime: 'Estimated Payoff Time',
    monthlyPayment: 'Monthly Payment',
    interestRate: 'Interest Rate',
    debtType: 'Debt Type',
    mortgage: 'Mortgage',
    autoLoan: 'Auto Loan',
    creditCard: 'Credit Card',
    personalLoan: 'Personal Loan',
    other: 'Other',
    avalanche: 'Avalanche',
    snowball: 'Snowball',
    consolidation: 'Consolidation',
    hybrid: 'Hybrid',
    addDebt: 'Add Debt',
    thisMonth: 'This Month',
    saved: 'Saved',
    variation: 'Variation',
    food: 'Food',
    transport: 'Transport',
    income: 'Income',
    entertainment: 'Entertainment',
    health: 'Health',
    salaryPayment: 'Salary Payment',
    wholeFoodsMarket: 'Whole Foods Market',
    uber: 'Uber',
    netflix: 'Netflix',
    pharmacyCVS: 'Pharmacy CVS',
    incomeVsExpenses: 'Income vs Expenses',
    january: 'Jan',
    february: 'Feb',
    march: 'Mar',
    april: 'Apr',
    may: 'May',
    expenses: 'Expenses',
    activeDebt: 'Active Debt',
    cards: 'Cards',
    averageInterest: 'Average Interest',
    debtObjective: 'Debt Objective',
    method: 'Method',
    timeline: 'Timeline',
    months: 'months',
    incomeLabel: 'Income',
    expensesLabel: 'Expenses',
    balanceLabel: 'Balance',
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
    of: 'of',
    shopping: 'Shopping',
    foodDrink: 'Food & Drink',
    groceries: 'Groceries',
    transportation: 'Transportation',
    dining: 'Dining',
    gymMembership: 'Gym Membership',
    amazon: 'Amazon',
    starbucks: 'Starbucks',
    salaryDeposit: 'Salary Deposit',
    wholefiles: 'Whole Foods',
    restaurant: 'Restaurant',
    cards_singular: 'card',
    cards_plural: 'cards',
    totalCreditDebt: 'Total Credit Debt',
    totalLimit: 'Total Limit',
    utilization: 'Utilization',
    yourCards: 'Your Cards',
    cardDetails: 'Card Details',
    edit: 'Edit',
    delete: 'Delete',
    utilizationHeader: 'Utilization',
    activeDebts: 'active debts',
    highestInterestRate: 'Highest Interest Rate',
    chooseStrategy: 'Choose Your Strategy',
    strategyDetails: 'Details of',
    advantage: 'Advantage',
    disadvantage: 'Disadvantage',
    timeToPayoff: 'Time to Payoff',
    totalEstimatedInterest: 'Total Estimated Interest',
    paymentOrder: 'Payment Order',
    order: 'Order',
    debt: 'Debt',
    rate: 'Rate',
    monthlyPaymentHeader: 'Monthly Payment',
    timeHeader: 'Time',
    years: 'years',
    subscription_singular: 'active subscription',
    subscription_plural: 'active subscriptions',
    monthlyCost: 'Monthly Cost',
    activeSubscriptions: 'Active Subscriptions',
    potentialSavings: 'Potential Savings',
    cancelEntertainment: 'If you cancel entertainment',
    filterByCategory: 'Filter by category',
    yourSubscriptions: 'Your Subscriptions',
    monthly: 'Monthly',
    yearly: 'Yearly',
    nextPayment: 'Next payment',
    cancel: 'Cancel',
    noSubscriptionsCategory: 'No subscriptions in this category',
    upcomingPayments: 'Upcoming Payments',
    subscription: 'Subscription',
    nextBillingDate: 'Next Payment',
    action: 'Action',
    in: 'In',
    days: 'days',
    aiRecommendations: 'AI Recommendations',
    consolidateStreaming: 'Consolidate Streaming',
    consolidateStreamingDesc: 'We detected 2 streaming services. Consider using only one to save $20/month.',
    adobeAlternative: 'Adobe Creative Cloud',
    adobeAlternativeDesc: 'It\'s your most expensive subscription. Consider alternatives like Figma or Canva.',
    optimalSpending: 'Optimal Spending',
    optimalSpendingDesc: 'Your total spending is {monthly}/month ({percentage}% of income)',
    underControl: 'Is under control',
    yearlyTotal: '/year',
    inCategory: 'in',
    all: 'All',
    scanReceiptSubtitle: 'Scan receipts to add transactions automatically',
    processing: 'Processing receipt...',
    analyzingOCR: 'Analyzing image with OCR',
    clickToUpload: 'Click to upload a receipt',
    dragOrUpload: 'Or drag an image here (JPG, PNG, HEIC)',
    scannedReceipts: 'Scanned Receipts',
    receiptAmount: 'Amount',
    receiptCard: 'Card',
    add: 'Add',
    discard: 'Discard',
    info: 'Information',
    supportsFormats: 'We support JPG, PNG, HEIC and other image formats',
    extractsAutomatically: 'Automatically extracts: merchant, amount, date and time',
    detectsCardDigits: 'Detects the last digits of your card',
    assignsCategory: 'Automatically assigns category',
    addsTransaction: 'Will add the transaction to your history',
    at: 'at',
    settingsTitle: 'Settings',
    manageAccount: 'Manage your account and preferences',
    accountTab: 'Account',
    notificationsTab: 'Notifications',
    privacyTab: 'Privacy',
    currentPlan: 'Current Plan',
    yourCurrentPlan: 'Your current plan',
    financeAIProPlan: 'FinanceAI Pro',
    renewalDate: 'Renewal on September 15, 2026',
    cancelSubscription: 'Cancel Subscription',
    changePlan: 'Change Plan',
    perMonth: '/month',
    currentPlanButton: 'Current Plan',
    language: 'Language',
    accountSection: 'Account',
    emailLabel: 'Email',
    changePassword: 'Change Password',
    legalSection: 'Legal',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    legalTerms: 'Legal Terms',
    planFree: 'Free',
    planPersonal: 'Personal',
    planPro: 'Pro',
    planBusiness: 'Business',
    featureBasicDashboard: 'Basic dashboard',
    featureLimitedTx: '5 transactions/month',
    featureNoAI: 'No AI',
    featureCompleteDashboard: 'Complete dashboard',
    featureUnlimitedTx: 'Unlimited transactions',
    featureBasicAI: 'Basic AI Assistant',
    featureScanReceipts: 'Receipt scanner',
    featureEverythingPersonal: 'Everything in Personal',
    featureAdvancedAI: 'Advanced AI',
    featureExpenseAnalysis: 'Expense analysis',
    featureExportPDF: 'PDF/CSV export',
    featureEverythingPro: 'Everything in Pro',
    featureMultiProfiles: '5 profiles',
    featurePrioritySupport: 'Priority support',
    featureAPIAccess: 'API access',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('es');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    try {
      const saved = localStorage.getItem('financeai-lang') as Language | null;
      if (saved && ['es', 'en'].includes(saved)) {
        setLanguageState(saved);
      }
    } catch {}
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('financeai-lang', lang);
    } catch {}
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  if (!mounted) return <>{children}</>;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  
  if (!context) {
    return {
      language: 'es',
      setLanguage: () => {},
      t: (key: string) => key,
    };
  }
  
  return context;
};
